//! Roc Platform ABI
//!
//! This file defines the Rust interface for hosted functions in a Roc platform.
//! It is automatically generated by the Roc glue generator.
//!
//! Hosted argument ownership:
//! - Roc transfers ownership of refcounted arguments to the hosted function.
//! - The hosted function must decref owned refcounted arguments when done.
//! - If the host stores or returns an argument, it must retain or transfer ownership explicitly.
//!
//! Import this module from the platform host and implement the listed hosted symbols
//! with the exact natural C ABI signatures shown below.

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(dead_code)]
#![allow(improper_ctypes)]
#![allow(improper_ctypes_definitions)]
// `no_roc_std_helpers` is supplied by host build tooling and cannot be registered from source.
#![allow(unexpected_cfgs)]

use core::ffi::c_void;
use core::sync::atomic::{fence, AtomicIsize, Ordering};
#[cfg(not(no_roc_std_helpers))]
use std::alloc::Layout;

/// Runtime representation of Roc's fixed-point `Dec` value.
///
/// `num` stores the decimal value scaled by 10^18.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct RocDec {
    pub num: i128,
}

const _: [(); 16] = [(); core::mem::size_of::<RocDec>()];
const _: [(); 16] = [(); core::mem::align_of::<RocDec>()];

#[cfg(target_arch = "x86_64")]
type RocU8x16Native = core::arch::x86_64::__m128i;
#[cfg(target_arch = "x86_64")]
type RocI8x16Native = core::arch::x86_64::__m128i;
#[cfg(target_arch = "x86_64")]
type RocU16x8Native = core::arch::x86_64::__m128i;
#[cfg(target_arch = "x86_64")]
type RocI16x8Native = core::arch::x86_64::__m128i;
#[cfg(target_arch = "x86_64")]
type RocU32x4Native = core::arch::x86_64::__m128i;
#[cfg(target_arch = "x86_64")]
type RocI32x4Native = core::arch::x86_64::__m128i;
#[cfg(target_arch = "x86_64")]
type RocU64x2Native = core::arch::x86_64::__m128i;
#[cfg(target_arch = "x86_64")]
type RocI64x2Native = core::arch::x86_64::__m128i;
#[cfg(target_arch = "aarch64")]
type RocU8x16Native = core::arch::aarch64::uint8x16_t;
#[cfg(target_arch = "aarch64")]
type RocI8x16Native = core::arch::aarch64::int8x16_t;
#[cfg(target_arch = "aarch64")]
type RocU16x8Native = core::arch::aarch64::uint16x8_t;
#[cfg(target_arch = "aarch64")]
type RocI16x8Native = core::arch::aarch64::int16x8_t;
#[cfg(target_arch = "aarch64")]
type RocU32x4Native = core::arch::aarch64::uint32x4_t;
#[cfg(target_arch = "aarch64")]
type RocI32x4Native = core::arch::aarch64::int32x4_t;
#[cfg(target_arch = "aarch64")]
type RocU64x2Native = core::arch::aarch64::uint64x2_t;
#[cfg(target_arch = "aarch64")]
type RocI64x2Native = core::arch::aarch64::int64x2_t;
#[cfg(target_arch = "wasm32")]
type RocU8x16Native = core::arch::wasm32::v128;
#[cfg(target_arch = "wasm32")]
type RocI8x16Native = core::arch::wasm32::v128;
#[cfg(target_arch = "wasm32")]
type RocU16x8Native = core::arch::wasm32::v128;
#[cfg(target_arch = "wasm32")]
type RocI16x8Native = core::arch::wasm32::v128;
#[cfg(target_arch = "wasm32")]
type RocU32x4Native = core::arch::wasm32::v128;
#[cfg(target_arch = "wasm32")]
type RocI32x4Native = core::arch::wasm32::v128;
#[cfg(target_arch = "wasm32")]
type RocU64x2Native = core::arch::wasm32::v128;
#[cfg(target_arch = "wasm32")]
type RocI64x2Native = core::arch::wasm32::v128;

macro_rules! roc_simd_type {
    ($name:ident, $native:ident) => {
        #[repr(transparent)]
        #[derive(Clone, Copy)]
        pub struct $name(pub $native);
        const _: [(); 16] = [(); core::mem::size_of::<$name>()];
        const _: [(); 16] = [(); core::mem::align_of::<$name>()];
    };
}
roc_simd_type!(RocU8x16, RocU8x16Native);
roc_simd_type!(RocI8x16, RocI8x16Native);
roc_simd_type!(RocU16x8, RocU16x8Native);
roc_simd_type!(RocI16x8, RocI16x8Native);
roc_simd_type!(RocU32x4, RocU32x4Native);
roc_simd_type!(RocI32x4, RocI32x4Native);
roc_simd_type!(RocU64x2, RocU64x2Native);
roc_simd_type!(RocI64x2, RocI64x2Native);


/// Runtime representation of an opaque `Box(T)` value.
pub type RocBox = *mut c_void;

/// Host-internal allocator and diagnostic context used by helper functions in this file.
///
/// Compiled Roc code does not receive this value. The real host ABI is the set of direct
/// linker symbols declared below (`roc_alloc`, hosted symbols, and provided entrypoints).
#[repr(C)]
pub struct RocHost {
    pub env: *mut c_void,
    pub roc_alloc: extern "C" fn(*mut RocHost, usize, usize) -> *mut c_void,
    pub roc_dealloc: extern "C" fn(*mut RocHost, *mut c_void, usize),
    pub roc_realloc: extern "C" fn(*mut RocHost, *mut c_void, usize, usize) -> *mut c_void,
    pub roc_dbg: extern "C" fn(*mut RocHost, *const u8, usize),
    pub roc_expect_failed: extern "C" fn(*mut RocHost, *const u8, usize),
    pub roc_crashed: extern "C" fn(*mut RocHost, *const u8, usize),
}

impl RocHost {
    /// Allocate memory with the given alignment and length.
    ///
    /// # Safety
    /// The returned pointer must be used only according to Roc allocation layout
    /// rules and later released through the matching host deallocator.
    #[inline]
    pub unsafe fn alloc(&self, alignment: usize, length: usize) -> *mut c_void {
        let host = self as *const RocHost as *mut RocHost;
        (self.roc_alloc)(host, length, alignment)
    }

    /// Deallocate memory previously allocated with `alloc`.
    ///
    /// # Safety
    /// `ptr` must have been allocated by this host with the same alignment and must
    /// not be used after this call.
    #[inline]
    pub unsafe fn dealloc(&self, ptr: *mut c_void, alignment: usize) {
        let host = self as *const RocHost as *mut RocHost;
        (self.roc_dealloc)(host, ptr, alignment);
    }

    /// Reallocate memory to a new size.
    ///
    /// # Safety
    /// `old_ptr` must have been allocated by this host with the same alignment.
    /// The returned pointer replaces `old_ptr`; the old pointer must not be used.
    #[inline]
    pub unsafe fn realloc(
        &self,
        old_ptr: *mut c_void,
        alignment: usize,
        new_length: usize,
    ) -> *mut c_void {
        let host = self as *const RocHost as *mut RocHost;
        (self.roc_realloc)(host, old_ptr, new_length, alignment)
    }
}

#[inline]
fn checked_add_usize(left: usize, right: usize, context: &str) -> usize {
    left.checked_add(right).expect(context)
}

#[inline]
fn checked_mul_usize(left: usize, right: usize, context: &str) -> usize {
    left.checked_mul(right).expect(context)
}

#[inline]
fn shifted_capacity(capacity: usize) -> usize {
    capacity.checked_shl(1).expect("Roc capacity does not fit shifted representation")
}

/// Uniform ABI function pointer stored in `RocErasedCallablePayload`.
pub type RocErasedCallableFn = extern "C" fn(*mut RocHost, *mut u8, *const u8, *mut u8);

/// Final-drop callback for inline erased-callable captures.
pub type RocErasedCallableOnDrop = extern "C" fn(*mut u8, *mut RocHost);

/// Payload header for `Box(function)`.
#[repr(C)]
#[derive(Debug, Clone, Copy)]
pub struct RocErasedCallablePayload {
    pub callable_fn_ptr: RocErasedCallableFn,
    pub on_drop: Option<RocErasedCallableOnDrop>,
}

const _: () = assert!(core::mem::size_of::<RocErasedCallablePayload>() == 2 * core::mem::size_of::<usize>(), "RocErasedCallablePayload size mismatch");
const _: () = assert!(core::mem::offset_of!(RocErasedCallablePayload, callable_fn_ptr) == 0, "RocErasedCallablePayload.callable_fn_ptr offset mismatch");
const _: () = assert!(core::mem::offset_of!(RocErasedCallablePayload, on_drop) == core::mem::size_of::<usize>(), "RocErasedCallablePayload.on_drop offset mismatch");

/// Runtime representation of `Box(function)`.
pub type RocErasedCallable = *mut u8;

pub const ROC_ERASED_CALLABLE_CAPTURE_ALIGNMENT: usize = 16;
pub const ROC_ERASED_CALLABLE_PAYLOAD_ALIGNMENT: usize = 16;
pub const ROC_ERASED_CALLABLE_CAPTURE_OFFSET: usize =
    (core::mem::size_of::<RocErasedCallablePayload>() + 15) & !15;

#[inline]
pub fn roc_erased_callable_payload_size(capture_size: usize) -> usize {
    checked_add_usize(
        ROC_ERASED_CALLABLE_CAPTURE_OFFSET,
        capture_size,
        "Roc erased-callable payload size overflow",
    )
}

#[inline]
/// # Safety
/// `callable` must be a non-null Roc erased-callable data pointer.
pub unsafe fn roc_erased_callable_payload_ptr(callable: RocErasedCallable) -> *mut RocErasedCallablePayload {
    callable as *mut RocErasedCallablePayload
}

#[inline]
/// # Safety
/// `callable` must be a non-null Roc erased-callable data pointer.
pub unsafe fn roc_erased_callable_capture_ptr(callable: RocErasedCallable) -> *mut u8 {
    callable.add(ROC_ERASED_CALLABLE_CAPTURE_OFFSET)
}

/// Allocate a Roc erased callable payload.
///
/// # Safety
/// The caller must initialize and use the returned callable according to Roc's
/// erased-callable ABI. `callable_fn_ptr` and `on_drop` must have matching ABI
/// signatures for the captured payload.
pub unsafe fn roc_erased_callable_allocate(
    roc_host: &RocHost,
    callable_fn_ptr: RocErasedCallableFn,
    on_drop: Option<RocErasedCallableOnDrop>,
    capture_size: usize,
) -> RocErasedCallable {
    let ptr_width = core::mem::size_of::<usize>();
    let alignment = core::cmp::max(ptr_width, ROC_ERASED_CALLABLE_PAYLOAD_ALIGNMENT);
    let extra_bytes = core::cmp::max(ptr_width, ROC_ERASED_CALLABLE_PAYLOAD_ALIGNMENT);
    let total = checked_add_usize(
        extra_bytes,
        roc_erased_callable_payload_size(capture_size),
        "Roc erased-callable allocation size overflow",
    );
    let base = roc_host.alloc(alignment, total) as *mut u8;
    let data = base.add(extra_bytes);
    let rc = data.sub(core::mem::size_of::<isize>()) as *mut isize;
    *rc = 1;
    let payload = roc_erased_callable_payload_ptr(data);
    *payload = RocErasedCallablePayload { callable_fn_ptr, on_drop };
    data
}

/// Payload drop callback for a boxed value.
///
/// The callback receives the boxed payload data pointer and must recursively
/// decref any Roc refcounted values inside the payload. It must not free the
/// box allocation; `decref_box_with` and `free_box_with` free it after the callback.
pub type RocBoxPayloadDecref = extern "C" fn(*mut c_void, *mut RocHost);

/// Increment the refcount of a boxed payload data pointer.
///
/// # Safety
/// `data_ptr` must be a valid Roc box payload pointer. The caller must ensure
/// that the extra retained references are balanced by later decrefs.
pub unsafe fn incref_box(data_ptr: RocBox, amount: isize) {
    let data = match box_data_ptr(data_ptr) {
        Some(ptr) => ptr,
        None => return,
    };
    let rc = box_refcount_ptr(data);
    if unsafe { (*rc).load(Ordering::Relaxed) } == 0 {
        return; // REFCOUNT_STATIC_DATA
    }
    unsafe {
        (*rc).fetch_add(amount, Ordering::Relaxed);
    }
}

/// Allocate a Roc box and return a pointer to its payload data.
///
/// # Safety
/// The returned payload memory is uninitialized. The caller must initialize it
/// according to the Roc type before exposing it to safe APIs or Roc code.
pub unsafe fn allocate_box(
    payload_size: usize,
    payload_alignment: usize,
    payload_contains_refcounted: bool,
    roc_host: &RocHost,
) -> RocBox {
    let ptr_width = core::mem::size_of::<usize>();
    let required_space = if payload_contains_refcounted { checked_mul_usize(2, ptr_width, "Roc box header size overflow") } else { ptr_width };
    let header_bytes = required_space.max(payload_alignment);
    let alloc_alignment = ptr_width.max(payload_alignment);
    let total = checked_add_usize(header_bytes, payload_size, "Roc box allocation size overflow");
    let base = roc_host.alloc(alloc_alignment, total) as *mut u8;
    let data = base.add(header_bytes);
    unsafe {
        let rc = data.sub(core::mem::size_of::<isize>()) as *mut isize;
        *rc = 1;
    }
    data as RocBox
}

/// Decrement a pointer-aligned boxed payload with no Roc refcounted values.
///
/// # Safety
/// `data_ptr` must be a valid Roc box payload pointer owned by this reference.
pub unsafe fn decref_box(data_ptr: RocBox, roc_host: &RocHost) {
    unsafe {
        decref_box_with(data_ptr, core::mem::align_of::<usize>(), false, None, roc_host);
    }
}

/// Increment a boxed function closure.
///
/// # Safety
/// `callable` must be a valid Roc erased-callable payload pointer.
pub unsafe fn incref_erased_callable(callable: RocErasedCallable, amount: isize) {
    unsafe {
        incref_box(callable as RocBox, amount);
    }
}

/// Decrement a boxed function closure and run its capture drop callback on final release.
///
/// # Safety
/// `callable` must be a valid Roc erased-callable payload pointer owned by this reference.
pub unsafe fn decref_erased_callable(callable: RocErasedCallable, roc_host: &RocHost) {
    unsafe {
        decref_box_with(
            callable as RocBox,
            ROC_ERASED_CALLABLE_PAYLOAD_ALIGNMENT,
            false,
            Some(drop_erased_callable_payload),
            roc_host,
        );
    }
}

extern "C" fn drop_erased_callable_payload(data_ptr: *mut c_void, roc_host: *mut RocHost) {
    if data_ptr.is_null() || roc_host.is_null() {
        return;
    }
    unsafe {
        let callable = data_ptr as RocErasedCallable;
        let payload = roc_erased_callable_payload_ptr(callable);
        if let Some(on_drop) = (*payload).on_drop {
            on_drop(roc_erased_callable_capture_ptr(callable), roc_host);
        }
    }
}

/// Decrement a boxed payload and run payload teardown when this is the final ref.
///
/// `payload_contains_refcounted` must match the value passed to `allocate_box`:
/// it determines the box header size, and is independent of whether a
/// `payload_decref` teardown callback is supplied. A host resource handle such
/// as `Box(U64)` holding a raw pointer has `payload_contains_refcounted: false`
/// even when it provides a teardown callback to free the underlying resource.
///
/// # Safety
/// `data_ptr` must be a valid Roc box payload pointer owned by this reference,
/// and `payload_alignment`/`payload_contains_refcounted` must match allocation.
pub unsafe fn decref_box_with(
    data_ptr: RocBox,
    payload_alignment: usize,
    payload_contains_refcounted: bool,
    payload_decref: Option<RocBoxPayloadDecref>,
    roc_host: &RocHost,
) {
    let data = match box_data_ptr(data_ptr) {
        Some(ptr) => ptr,
        None => return,
    };
    let rc = box_refcount_ptr(data);
    if unsafe { (*rc).load(Ordering::Relaxed) } == 0 {
        return; // REFCOUNT_STATIC_DATA
    }
    let prev = unsafe { (*rc).fetch_sub(1, Ordering::Release) };
    if prev == 1 {
        fence(Ordering::Acquire);
        if let Some(callback) = payload_decref {
            callback(data_ptr, roc_host as *const RocHost as *mut RocHost);
        }
        free_box_allocation(data, payload_alignment, payload_contains_refcounted, roc_host);
    }
}

/// Free a boxed payload allocation immediately after running payload teardown.
///
/// See `decref_box_with` for the meaning of `payload_contains_refcounted`.
///
/// # Safety
/// `data_ptr` must be a valid Roc box payload pointer that will not be used after this call.
pub unsafe fn free_box_with(
    data_ptr: RocBox,
    payload_alignment: usize,
    payload_contains_refcounted: bool,
    payload_decref: Option<RocBoxPayloadDecref>,
    roc_host: &RocHost,
) {
    let data = match box_data_ptr(data_ptr) {
        Some(ptr) => ptr,
        None => return,
    };
    if let Some(callback) = payload_decref {
        callback(data_ptr, roc_host as *const RocHost as *mut RocHost);
    }
    free_box_allocation(data, payload_alignment, payload_contains_refcounted, roc_host);
}

/// Return true when a boxed payload data pointer has exactly one live ref.
pub fn is_unique_box(data_ptr: RocBox) -> bool {
    let data = match box_data_ptr(data_ptr) {
        Some(ptr) => ptr,
        None => return true,
    };
    let rc = box_refcount_ptr(data);
    unsafe { (*rc).load(Ordering::Acquire) == 1 }
}

fn box_data_ptr(data_ptr: RocBox) -> Option<*mut u8> {
    if data_ptr.is_null() {
        None
    } else {
        Some(data_ptr as *mut u8)
    }
}

fn box_refcount_ptr(data: *mut u8) -> *mut AtomicIsize {
    unsafe { data.sub(core::mem::size_of::<isize>()) as *mut AtomicIsize }
}

fn free_box_allocation(
    data: *mut u8,
    payload_alignment: usize,
    payload_contains_refcounted: bool,
    roc_host: &RocHost,
) {
    let ptr_width = core::mem::size_of::<usize>();
    let required_space = if payload_contains_refcounted { checked_mul_usize(2, ptr_width, "Roc box header size overflow") } else { ptr_width };
    let header_bytes = required_space.max(payload_alignment);
    let alloc_alignment = ptr_width.max(payload_alignment);
    let base = unsafe { data.sub(header_bytes) } as *mut c_void;
    unsafe {
        roc_host.dealloc(base, alloc_alignment);
    }
}

/// A Roc string value. Small strings (up to 23 bytes on 64-bit) are stored inline;
/// larger strings are heap-allocated with a reference count.
///
/// `bytes` is never tagged. Operations, host code, glue code, and object-file
/// relocations can use it directly as the UTF-8 byte pointer for non-small
/// strings. Seamless-slice tagging lives in `capacity_or_alloc_ptr` instead.
/// Big-string capacity is stored shifted left by one bit, so max capacity is
/// essentially `isize::MAX` bytes: about 2 GiB on 32-bit targets and 8 EiB on
/// 64-bit targets.
///
/// This type is ABI-compatible with the Zig RocStr (24 bytes, `#[repr(C)]`).
#[repr(C)]
#[derive(Clone, Copy)]
pub struct RocStr {
    pub bytes: *mut u8,
    pub capacity_or_alloc_ptr: usize,
    pub length: usize,
}

const _: () = assert!(core::mem::size_of::<RocStr>() == 3 * core::mem::size_of::<usize>(), "RocStr size mismatch");
const _: () = assert!(core::mem::align_of::<RocStr>() == core::mem::align_of::<usize>(), "RocStr alignment mismatch");
const _: () = assert!(core::mem::offset_of!(RocStr, bytes) == 0, "RocStr.bytes offset mismatch");
const _: () = assert!(core::mem::offset_of!(RocStr, capacity_or_alloc_ptr) == core::mem::size_of::<usize>(), "RocStr.capacity_or_alloc_ptr offset mismatch");
const _: () = assert!(core::mem::offset_of!(RocStr, length) == 2 * core::mem::size_of::<usize>(), "RocStr.length offset mismatch");

const ROC_STR_SIZE: usize = core::mem::size_of::<RocStr>();
const ROC_SMALL_STR_MAX_LEN: usize = ROC_STR_SIZE - 1;
const ROC_SMALL_STR_BIT: usize = isize::MIN as usize;
const ROC_SEAMLESS_SLICE_TAG: usize = 1;

impl RocStr {
    /// Return an empty RocStr (small string with zero length).
    pub fn empty() -> Self {
        Self {
            bytes: core::ptr::null_mut(),
            capacity_or_alloc_ptr: 0,
            length: ROC_SMALL_STR_BIT,
        }
    }

    /// Return true if this string is stored inline (small string optimization).
    #[inline]
    pub fn is_small_str(&self) -> bool {
        (self.length as isize) < 0
    }

    /// Return true if this string is a seamless slice into another allocation.
    #[inline]
    pub fn is_seamless_slice(&self) -> bool {
        !self.is_small_str() && (self.capacity_or_alloc_ptr & ROC_SEAMLESS_SLICE_TAG) != 0
    }

    /// Return the length of the string in bytes.
    #[inline]
    pub fn len(&self) -> usize {
        if self.is_small_str() {
            let bytes_ptr = self as *const Self as *const u8;
            let last_byte = unsafe { *bytes_ptr.add(ROC_STR_SIZE - 1) };
            (last_byte ^ 0b1000_0000) as usize
        } else {
            self.length
        }
    }

    /// Return true if the string has zero length.
    #[inline]
    pub fn is_empty(&self) -> bool {
        self.len() == 0
    }

    /// Return the string contents as a byte slice.
    pub fn as_slice(&self) -> &[u8] {
        let ptr = self.as_u8_ptr();
        unsafe { core::slice::from_raw_parts(ptr, self.len()) }
    }

    /// Return a pointer to the raw UTF-8 bytes.
    #[inline]
    pub fn as_u8_ptr(&self) -> *const u8 {
        if self.is_small_str() {
            self as *const Self as *const u8
        } else {
            self.bytes as *const u8
        }
    }

    /// Return the string contents as a `&str`.
    pub fn as_str(&self) -> &str {
        core::str::from_utf8(self.as_slice()).expect("RocStr contained invalid UTF-8")
    }

    /// Create a RocStr from a UTF-8 byte slice, using `roc_host` for heap allocation if needed.
    pub fn from_slice(slice: &[u8], roc_host: &RocHost) -> Self {
        core::str::from_utf8(slice).expect("RocStr::from_slice requires valid UTF-8");
        if slice.len() < ROC_STR_SIZE {
            let mut result = Self::empty();
            let ptr = &mut result as *mut Self as *mut u8;
            unsafe {
                core::ptr::copy_nonoverlapping(slice.as_ptr(), ptr, slice.len());
                *ptr.add(ROC_STR_SIZE - 1) = (slice.len() as u8) | 0b1000_0000;
            }
            result
        } else {
            let ptr_width = core::mem::size_of::<usize>();
            let total = checked_add_usize(ptr_width, slice.len(), "RocStr allocation size overflow");
            let base = unsafe { roc_host.alloc(core::mem::align_of::<usize>(), total) };
            let data_ptr = unsafe { (base as *mut u8).add(ptr_width) };
            // Write refcount = 1
            unsafe {
                let rc = (data_ptr as *mut isize).sub(1);
                *rc = 1;
                core::ptr::copy_nonoverlapping(slice.as_ptr(), data_ptr, slice.len());
            }
            Self {
                bytes: data_ptr,
                capacity_or_alloc_ptr: shifted_capacity(slice.len()),
                length: slice.len(),
            }
        }
    }

    /// Create a RocStr from a `&str`.
    pub fn from_str(s: &str, roc_host: &RocHost) -> Self {
        Self::from_slice(s.as_bytes(), roc_host)
    }

    /// Decrement the reference count; frees the allocation when it reaches zero.
    ///
    /// # Safety
    /// `self` must own one live Roc reference. Calling this more than once for the
    /// same ownership reference may double-free.
    pub unsafe fn decref(self, roc_host: &RocHost) {
        if self.is_small_str() {
            return;
        }
        let alloc_ptr = self.get_allocation_ptr();
        if alloc_ptr.is_null() {
            return;
        }
        let rc = unsafe { (alloc_ptr as *mut AtomicIsize).sub(1) };
        if unsafe { (*rc).load(Ordering::Relaxed) } == 0 {
            return; // REFCOUNT_STATIC_DATA — bytes are in read-only memory
        }
        let prev = unsafe { (*rc).fetch_sub(1, Ordering::Release) };
        if prev == 1 {
            fence(Ordering::Acquire);
            let ptr_width = core::mem::size_of::<usize>();
            let base = unsafe { alloc_ptr.sub(ptr_width) } as *mut c_void;
            unsafe {
                roc_host.dealloc(base, core::mem::align_of::<usize>());
            }
        }
    }

    /// Increment the reference count by `amount`.
    ///
    /// # Safety
    /// `self` must point at a live Roc allocation. The retained references must
    /// be balanced by later decrefs.
    pub unsafe fn incref(self, amount: isize) {
        if self.is_small_str() {
            return;
        }
        let alloc_ptr = self.get_allocation_ptr();
        if alloc_ptr.is_null() {
            return;
        }
        let rc = unsafe { (alloc_ptr as *mut AtomicIsize).sub(1) };
        if unsafe { (*rc).load(Ordering::Relaxed) } == 0 {
            return; // REFCOUNT_STATIC_DATA
        }
        unsafe {
            (*rc).fetch_add(amount, Ordering::Relaxed);
        }
    }

    /// Return true if this string has a reference count of exactly one.
    pub fn is_unique(&self) -> bool {
        if self.is_small_str() {
            return true;
        }
        let alloc_ptr = self.get_allocation_ptr();
        if alloc_ptr.is_null() {
            return true;
        }
        unsafe {
            let rc = (alloc_ptr as *const AtomicIsize).sub(1);
            let count = (*rc).load(Ordering::Acquire);
            count == 0 || count == 1
        }
    }

    fn get_allocation_ptr(&self) -> *mut u8 {
        if self.is_seamless_slice() {
            (self.capacity_or_alloc_ptr & !ROC_SEAMLESS_SLICE_TAG) as *mut u8
        } else {
            self.bytes
        }
    }
}

impl core::fmt::Debug for RocStr {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.debug_struct("RocStr")
            .field("len", &self.len())
            .field("is_small", &self.is_small_str())
            .finish()
    }
}

/// A generic Roc list. Elements are reference-counted and heap-allocated.
///
/// When `ELEMENTS_REFCOUNTED` is true (the default via `RocList<T>`), an extra
/// `ptr_width` bytes are reserved in the allocation header for the element count,
/// matching the Roc runtime's `allocateWithRefcount` layout.
pub type RocList<T> = RocListWith<T, true>;

/// Parameterized list constructor; use `RocList<T>` for refcounted elements.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct RocListWith<T, const ELEMENTS_REFCOUNTED: bool> {
    pub elements: *mut T,
    pub length: usize,
    pub capacity_or_alloc_ptr: usize,
}

const _: () = assert!(core::mem::size_of::<RocList<u8>>() == 3 * core::mem::size_of::<usize>(), "RocList size mismatch");
const _: () = assert!(core::mem::align_of::<RocList<u8>>() == core::mem::align_of::<usize>(), "RocList alignment mismatch");
const _: () = assert!(core::mem::offset_of!(RocList<u8>, elements) == 0, "RocList.elements offset mismatch");
const _: () = assert!(core::mem::offset_of!(RocList<u8>, length) == core::mem::size_of::<usize>(), "RocList.length offset mismatch");
const _: () = assert!(core::mem::offset_of!(RocList<u8>, capacity_or_alloc_ptr) == 2 * core::mem::size_of::<usize>(), "RocList.capacity_or_alloc_ptr offset mismatch");

impl<T, const ELEMENTS_REFCOUNTED: bool> RocListWith<T, ELEMENTS_REFCOUNTED> {
    #[inline]
    fn header_bytes() -> usize {
        let ptr_width = core::mem::size_of::<usize>();
        let required_space = if ELEMENTS_REFCOUNTED { checked_mul_usize(2, ptr_width, "RocList header size overflow") } else { ptr_width };
        required_space.max(core::mem::align_of::<T>())
    }

    /// Return an empty RocList.
    pub fn empty() -> Self {
        Self {
            elements: core::ptr::null_mut(),
            length: 0,
            capacity_or_alloc_ptr: 0,
        }
    }

    /// Return the number of elements in the list.
    #[inline]
    pub fn len(&self) -> usize {
        self.length
    }

    /// Return true if the list has zero elements.
    #[inline]
    pub fn is_empty(&self) -> bool {
        self.length == 0
    }

    /// Return true if this list is a seamless slice into another allocation.
    /// Slices share the rc slot with their backing allocation; the alloc ptr is
    /// encoded in `capacity_or_alloc_ptr` with the low bit set.
    #[inline]
    pub fn is_seamless_slice(&self) -> bool {
        (self.capacity_or_alloc_ptr & 1) != 0
    }

    /// Resolve `self` to the start of its backing allocation (the element block
    /// just after the rc slot). Returns `null` for empty lists. Handles both
    /// whole-backing and seamless-slice forms.
    fn get_allocation_ptr(&self) -> *mut u8 {
        if self.is_seamless_slice() {
            (self.capacity_or_alloc_ptr & !1) as *mut u8
        } else {
            self.elements as *mut u8
        }
    }

    fn allocation_element_count(&self) -> usize {
        if self.is_seamless_slice() && ELEMENTS_REFCOUNTED {
            let alloc_ptr = self.get_allocation_ptr();
            if alloc_ptr.is_null() {
                return 0;
            }
            unsafe {
                let ptr = alloc_ptr as *const usize;
                *ptr.sub(2)
            }
        } else {
            self.length
        }
    }

    /// Return the list elements as a slice.
    pub fn as_slice(&self) -> &[T] {
        if self.elements.is_null() {
            &[]
        } else {
            unsafe { core::slice::from_raw_parts(self.elements, self.length) }
        }
    }

    /// Return all items in the backing allocation, not just this slice.
    pub fn allocation_items(&self) -> &[T] {
        if self.elements.is_null() {
            &[]
        } else {
            unsafe { core::slice::from_raw_parts(self.get_allocation_ptr() as *const T, self.allocation_element_count()) }
        }
    }

    /// Allocate a new list with space for `length` elements.
    ///
    /// # Safety
    /// The returned element memory is uninitialized while `length` is already
    /// set. The caller must initialize every element before exposing the list
    /// to safe APIs, Roc code, or generated refcount helpers.
    pub unsafe fn allocate(length: usize, roc_host: &RocHost) -> Self {
        if length == 0 {
            return Self::empty();
        }
        let align = core::mem::align_of::<T>().max(core::mem::align_of::<usize>());
        let header_bytes = Self::header_bytes();
        let data_bytes = checked_mul_usize(length, core::mem::size_of::<T>(), "RocList allocation element bytes overflow");
        let total = checked_add_usize(data_bytes, header_bytes, "RocList allocation size overflow");
        let base = roc_host.alloc(align, total);
        let data_ptr = (base as *mut u8).add(header_bytes);
        unsafe {
            let rc = (data_ptr as *mut isize).sub(1);
            *rc = 1;
            if ELEMENTS_REFCOUNTED {
                let count = (data_ptr as *mut usize).sub(2);
                *count = length;
            }
        }
        Self {
            elements: data_ptr as *mut T,
            length,
            capacity_or_alloc_ptr: shifted_capacity(length),
        }
    }

    /// Create a RocList from a slice, copying elements into a new allocation.
    ///
    /// # Safety
    /// This is a shallow copy. For element types that own Roc references, the
    /// caller must ensure each copied element is already retained for the new
    /// list or will not be decref'd through another owner.
    pub unsafe fn from_slice(slice: &[T], roc_host: &RocHost) -> Self where T: Copy {
        if slice.is_empty() {
            return Self::empty();
        }
        let list = unsafe { Self::allocate(slice.len(), roc_host) };
        unsafe {
            core::ptr::copy_nonoverlapping(
                slice.as_ptr(),
                list.elements,
                slice.len(),
            );
        }
        list
    }

    /// Decrement the reference count; frees the allocation when it reaches zero.
    ///
    /// # Safety
    /// `self` must own one live Roc list reference. Calling this more than once
    /// for the same ownership reference may double-free.
    pub unsafe fn decref(self, roc_host: &RocHost) {
        if self.elements.is_null() {
            return;
        }
        let alloc_ptr = self.get_allocation_ptr();
        if alloc_ptr.is_null() {
            return;
        }
        let align = core::mem::align_of::<T>().max(core::mem::align_of::<usize>());
        let header_bytes = Self::header_bytes();
        let rc = unsafe { (alloc_ptr as *mut AtomicIsize).sub(1) };
        if unsafe { (*rc).load(Ordering::Relaxed) } == 0 {
            return; // REFCOUNT_STATIC_DATA — elements are in read-only memory
        }
        let prev = unsafe { (*rc).fetch_sub(1, Ordering::Release) };
        if prev == 1 {
            fence(Ordering::Acquire);
            let base = unsafe { alloc_ptr.sub(header_bytes) } as *mut c_void;
            unsafe {
                roc_host.dealloc(base, align);
            }
        }
    }

    /// Increment the reference count by `amount`.
    ///
    /// # Safety
    /// `self` must point at a live Roc list allocation. The retained references
    /// must be balanced by later decrefs.
    pub unsafe fn incref(self, amount: isize) {
        if self.elements.is_null() {
            return;
        }
        let alloc_ptr = self.get_allocation_ptr();
        if alloc_ptr.is_null() {
            return;
        }
        let rc = unsafe { (alloc_ptr as *mut AtomicIsize).sub(1) };
        if unsafe { (*rc).load(Ordering::Relaxed) } == 0 {
            return; // REFCOUNT_STATIC_DATA
        }
        unsafe {
            (*rc).fetch_add(amount, Ordering::Relaxed);
        }
    }

    /// Return true if this list has a reference count of exactly one.
    pub fn is_unique(&self) -> bool {
        let alloc_ptr = self.get_allocation_ptr();
        if alloc_ptr.is_null() {
            return true;
        }
        unsafe {
            let rc = (alloc_ptr as *const AtomicIsize).sub(1);
            let count = (*rc).load(Ordering::Acquire);
            count == 0 || count == 1
        }
    }

    /// Return true if this list's allocation has exactly one counted ref.
    pub fn has_one_ref(&self) -> bool {
        let alloc_ptr = self.get_allocation_ptr();
        if alloc_ptr.is_null() {
            return false;
        }
        unsafe {
            let rc = (alloc_ptr as *const AtomicIsize).sub(1);
            (*rc).load(Ordering::Acquire) == 1
        }
    }
}

impl<T: core::fmt::Debug, const ELEMENTS_REFCOUNTED: bool> core::fmt::Debug for RocListWith<T, ELEMENTS_REFCOUNTED> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.debug_list().entries(self.as_slice().iter()).finish()
    }
}

/// Element type for __AnonStruct_57e411f048803101
#[cfg(target_pointer_width = "32")]
#[repr(C)]
#[derive(Clone, Copy)]
pub struct AnonStruct57e411f048803101 {
    pub init: *mut c_void,
    pub update: *mut c_void,
    pub view: *mut c_void,
}

/// Element type for __AnonStruct_57e411f048803101
#[cfg(not(target_pointer_width = "32"))]
#[repr(C)]
#[derive(Clone, Copy)]
pub struct AnonStruct57e411f048803101 {
    pub init: *mut c_void,
    pub update: *mut c_void,
    pub view: *mut c_void,
}

#[cfg(target_pointer_width = "64")]
const _: () = assert!(core::mem::size_of::<AnonStruct57e411f048803101>() == 24, "AnonStruct57e411f048803101 size mismatch");
#[cfg(target_pointer_width = "64")]
const _: () = assert!(core::mem::align_of::<AnonStruct57e411f048803101>() == 8, "AnonStruct57e411f048803101 alignment mismatch");
#[cfg(target_pointer_width = "32")]
const _: () = assert!(core::mem::size_of::<AnonStruct57e411f048803101>() == 12, "AnonStruct57e411f048803101 size mismatch");
#[cfg(target_pointer_width = "32")]
const _: () = assert!(core::mem::align_of::<AnonStruct57e411f048803101>() == 4, "AnonStruct57e411f048803101 alignment mismatch");

/// Element type for __AnonStruct_3a8854a0aa6a1ebb
#[cfg(target_pointer_width = "32")]
#[repr(C)]
#[derive(Clone, Copy)]
pub struct AnonStruct3a8854a0aa6a1ebb {
    pub effects: RocList<Effect>,
    pub m: RocBox,
    pub sub: Subscriptions,
}

/// Element type for __AnonStruct_3a8854a0aa6a1ebb
#[cfg(not(target_pointer_width = "32"))]
#[repr(C)]
#[derive(Clone, Copy)]
pub struct AnonStruct3a8854a0aa6a1ebb {
    pub effects: RocList<Effect>,
    pub m: RocBox,
    pub sub: Subscriptions,
}

#[cfg(target_pointer_width = "64")]
const _: () = assert!(core::mem::size_of::<AnonStruct3a8854a0aa6a1ebb>() == 176, "AnonStruct3a8854a0aa6a1ebb size mismatch");
#[cfg(target_pointer_width = "64")]
const _: () = assert!(core::mem::align_of::<AnonStruct3a8854a0aa6a1ebb>() == 8, "AnonStruct3a8854a0aa6a1ebb alignment mismatch");
#[cfg(target_pointer_width = "32")]
const _: () = assert!(core::mem::size_of::<AnonStruct3a8854a0aa6a1ebb>() == 88, "AnonStruct3a8854a0aa6a1ebb size mismatch");
#[cfg(target_pointer_width = "32")]
const _: () = assert!(core::mem::align_of::<AnonStruct3a8854a0aa6a1ebb>() == 4, "AnonStruct3a8854a0aa6a1ebb alignment mismatch");

/// Element type for __AnonStruct_3b1714e0f1aad535
#[cfg(target_pointer_width = "32")]
#[repr(C)]
#[derive(Clone, Copy)]
pub struct AnonStruct3b1714e0f1aad535 {
    pub stream: TcpStream,
    pub data: RocListWith<u8, false>,
}

/// Element type for __AnonStruct_3b1714e0f1aad535
#[cfg(not(target_pointer_width = "32"))]
#[repr(C)]
#[derive(Clone, Copy)]
pub struct AnonStruct3b1714e0f1aad535 {
    pub stream: TcpStream,
    pub data: RocListWith<u8, false>,
}

#[cfg(target_pointer_width = "64")]
const _: () = assert!(core::mem::size_of::<AnonStruct3b1714e0f1aad535>() == 32, "AnonStruct3b1714e0f1aad535 size mismatch");
#[cfg(target_pointer_width = "64")]
const _: () = assert!(core::mem::align_of::<AnonStruct3b1714e0f1aad535>() == 8, "AnonStruct3b1714e0f1aad535 alignment mismatch");
#[cfg(target_pointer_width = "32")]
const _: () = assert!(core::mem::size_of::<AnonStruct3b1714e0f1aad535>() == 24, "AnonStruct3b1714e0f1aad535 size mismatch");
#[cfg(target_pointer_width = "32")]
const _: () = assert!(core::mem::align_of::<AnonStruct3b1714e0f1aad535>() == 8, "AnonStruct3b1714e0f1aad535 alignment mismatch");

/// Element type for TcpStream
#[cfg(target_pointer_width = "32")]
#[repr(C)]
#[derive(Clone, Copy)]
pub struct TcpStream {
    pub id: u64,
}

/// Element type for TcpStream
#[cfg(not(target_pointer_width = "32"))]
#[repr(C)]
#[derive(Clone, Copy)]
pub struct TcpStream {
    pub id: u64,
}

#[cfg(target_pointer_width = "64")]
const _: () = assert!(core::mem::size_of::<TcpStream>() == 8, "TcpStream size mismatch");
#[cfg(target_pointer_width = "64")]
const _: () = assert!(core::mem::align_of::<TcpStream>() == 8, "TcpStream alignment mismatch");
#[cfg(target_pointer_width = "32")]
const _: () = assert!(core::mem::size_of::<TcpStream>() == 8, "TcpStream size mismatch");
#[cfg(target_pointer_width = "32")]
const _: () = assert!(core::mem::align_of::<TcpStream>() == 8, "TcpStream alignment mismatch");

/// Element type for __AnonStruct_bba21047290b1d3a
#[cfg(target_pointer_width = "32")]
#[repr(C)]
#[derive(Clone, Copy)]
pub struct AnonStructBba21047290b1d3a {
    pub content: RocStr,
    pub filename: RocStr,
}

/// Element type for __AnonStruct_bba21047290b1d3a
#[cfg(not(target_pointer_width = "32"))]
#[repr(C)]
#[derive(Clone, Copy)]
pub struct AnonStructBba21047290b1d3a {
    pub content: RocStr,
    pub filename: RocStr,
}

#[cfg(target_pointer_width = "64")]
const _: () = assert!(core::mem::size_of::<AnonStructBba21047290b1d3a>() == 48, "AnonStructBba21047290b1d3a size mismatch");
#[cfg(target_pointer_width = "64")]
const _: () = assert!(core::mem::align_of::<AnonStructBba21047290b1d3a>() == 8, "AnonStructBba21047290b1d3a alignment mismatch");
#[cfg(target_pointer_width = "32")]
const _: () = assert!(core::mem::size_of::<AnonStructBba21047290b1d3a>() == 24, "AnonStructBba21047290b1d3a size mismatch");
#[cfg(target_pointer_width = "32")]
const _: () = assert!(core::mem::align_of::<AnonStructBba21047290b1d3a>() == 4, "AnonStructBba21047290b1d3a alignment mismatch");

/// Element type for Subscriptions
#[cfg(target_pointer_width = "32")]
#[repr(C)]
#[derive(Clone, Copy)]
pub struct Subscriptions {
    pub stdin: TryType33,
    pub accept_tcp_connection: TryType24,
    pub tcp_connect: TryType47,
    pub tcp_receive: TryType56,
}

/// Element type for Subscriptions
#[cfg(not(target_pointer_width = "32"))]
#[repr(C)]
#[derive(Clone, Copy)]
pub struct Subscriptions {
    pub stdin: TryType33,
    pub accept_tcp_connection: TryType24,
    pub tcp_connect: TryType47,
    pub tcp_receive: TryType56,
}

#[cfg(target_pointer_width = "64")]
const _: () = assert!(core::mem::size_of::<Subscriptions>() == 144, "Subscriptions size mismatch");
#[cfg(target_pointer_width = "64")]
const _: () = assert!(core::mem::align_of::<Subscriptions>() == 8, "Subscriptions alignment mismatch");
#[cfg(target_pointer_width = "32")]
const _: () = assert!(core::mem::size_of::<Subscriptions>() == 72, "Subscriptions size mismatch");
#[cfg(target_pointer_width = "32")]
const _: () = assert!(core::mem::align_of::<Subscriptions>() == 4, "Subscriptions alignment mismatch");

/// Element type for __AnonStruct_11c0d71a1110c7df
#[cfg(target_pointer_width = "32")]
#[repr(C)]
#[derive(Clone, Copy)]
pub struct AnonStruct11c0d71a1110c7df {
    pub host: RocStr,
    pub on_connected: RocErasedCallable,
    pub on_disconnected: RocErasedCallable,
    pub port: u16,
}

/// Element type for __AnonStruct_11c0d71a1110c7df
#[cfg(not(target_pointer_width = "32"))]
#[repr(C)]
#[derive(Clone, Copy)]
pub struct AnonStruct11c0d71a1110c7df {
    pub host: RocStr,
    pub on_connected: RocErasedCallable,
    pub on_disconnected: RocErasedCallable,
    pub port: u16,
}

#[cfg(target_pointer_width = "64")]
const _: () = assert!(core::mem::size_of::<AnonStruct11c0d71a1110c7df>() == 48, "AnonStruct11c0d71a1110c7df size mismatch");
#[cfg(target_pointer_width = "64")]
const _: () = assert!(core::mem::align_of::<AnonStruct11c0d71a1110c7df>() == 8, "AnonStruct11c0d71a1110c7df alignment mismatch");
#[cfg(target_pointer_width = "32")]
const _: () = assert!(core::mem::size_of::<AnonStruct11c0d71a1110c7df>() == 24, "AnonStruct11c0d71a1110c7df size mismatch");
#[cfg(target_pointer_width = "32")]
const _: () = assert!(core::mem::align_of::<AnonStruct11c0d71a1110c7df>() == 4, "AnonStruct11c0d71a1110c7df alignment mismatch");

/// Element type for __AnonStruct_3662079be59957c3
#[cfg(target_pointer_width = "32")]
#[repr(C)]
#[derive(Clone, Copy)]
pub struct AnonStruct3662079be59957c3 {
    pub address: RocStr,
    pub on_connected: RocErasedCallable,
    pub on_disconnected: RocErasedCallable,
    pub port: u16,
}

/// Element type for __AnonStruct_3662079be59957c3
#[cfg(not(target_pointer_width = "32"))]
#[repr(C)]
#[derive(Clone, Copy)]
pub struct AnonStruct3662079be59957c3 {
    pub address: RocStr,
    pub on_connected: RocErasedCallable,
    pub on_disconnected: RocErasedCallable,
    pub port: u16,
}

#[cfg(target_pointer_width = "64")]
const _: () = assert!(core::mem::size_of::<AnonStruct3662079be59957c3>() == 48, "AnonStruct3662079be59957c3 size mismatch");
#[cfg(target_pointer_width = "64")]
const _: () = assert!(core::mem::align_of::<AnonStruct3662079be59957c3>() == 8, "AnonStruct3662079be59957c3 alignment mismatch");
#[cfg(target_pointer_width = "32")]
const _: () = assert!(core::mem::size_of::<AnonStruct3662079be59957c3>() == 24, "AnonStruct3662079be59957c3 size mismatch");
#[cfg(target_pointer_width = "32")]
const _: () = assert!(core::mem::align_of::<AnonStruct3662079be59957c3>() == 4, "AnonStruct3662079be59957c3 alignment mismatch");

/// Element type for TerminalSettings
#[cfg(target_pointer_width = "32")]
#[repr(C)]
#[derive(Clone, Copy)]
pub struct TerminalSettings {
    pub width: u64,
    pub height: u64,
}

/// Element type for TerminalSettings
#[cfg(not(target_pointer_width = "32"))]
#[repr(C)]
#[derive(Clone, Copy)]
pub struct TerminalSettings {
    pub width: u64,
    pub height: u64,
}

#[cfg(target_pointer_width = "64")]
const _: () = assert!(core::mem::size_of::<TerminalSettings>() == 16, "TerminalSettings size mismatch");
#[cfg(target_pointer_width = "64")]
const _: () = assert!(core::mem::align_of::<TerminalSettings>() == 8, "TerminalSettings alignment mismatch");
#[cfg(target_pointer_width = "32")]
const _: () = assert!(core::mem::size_of::<TerminalSettings>() == 16, "TerminalSettings size mismatch");
#[cfg(target_pointer_width = "32")]
const _: () = assert!(core::mem::align_of::<TerminalSettings>() == 8, "TerminalSettings alignment mismatch");

/// Tag discriminant for Effect.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum EffectTag {
    Exit = 0,
    Print = 1,
    TcpSend = 2,
    WriteToFile = 3,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub union EffectPayload {
    pub exit: core::mem::ManuallyDrop<u16>,
    pub print: core::mem::ManuallyDrop<RocStr>,
    pub tcp_send: core::mem::ManuallyDrop<AnonStruct3b1714e0f1aad535>,
    pub write_to_file: core::mem::ManuallyDrop<AnonStructBba21047290b1d3a>,
}

#[cfg(target_pointer_width = "32")]
#[repr(align(8))]
#[derive(Clone, Copy)]
pub struct EffectPayloadAlignment;

/// Tag union: Effect
#[cfg(target_pointer_width = "32")]
#[repr(C)]
#[derive(Clone, Copy)]
pub struct Effect {
    pub _payload_alignment: [EffectPayloadAlignment; 0],
    pub payload: [u8; 24],
    pub tag: EffectTag,
}

/// Tag union: Effect
#[cfg(not(target_pointer_width = "32"))]
#[repr(C)]
#[derive(Clone, Copy)]
pub struct Effect {
    pub payload: EffectPayload,
    pub tag: EffectTag,
}

impl Effect {
    #[cfg(target_pointer_width = "32")]
    pub fn payload_exit(&self) -> u16 {
        unsafe { core::ptr::read(self.payload.as_ptr() as *const u16) }
    }

    #[cfg(not(target_pointer_width = "32"))]
    pub fn payload_exit(&self) -> u16 {
        unsafe { core::mem::ManuallyDrop::into_inner(self.payload.exit) }
    }

    #[cfg(target_pointer_width = "32")]
    pub fn payload_print(&self) -> RocStr {
        unsafe { core::ptr::read(self.payload.as_ptr() as *const RocStr) }
    }

    #[cfg(not(target_pointer_width = "32"))]
    pub fn payload_print(&self) -> RocStr {
        unsafe { core::mem::ManuallyDrop::into_inner(self.payload.print) }
    }

    #[cfg(target_pointer_width = "32")]
    pub fn payload_tcp_send(&self) -> AnonStruct3b1714e0f1aad535 {
        unsafe { core::ptr::read(self.payload.as_ptr() as *const AnonStruct3b1714e0f1aad535) }
    }

    #[cfg(not(target_pointer_width = "32"))]
    pub fn payload_tcp_send(&self) -> AnonStruct3b1714e0f1aad535 {
        unsafe { core::mem::ManuallyDrop::into_inner(self.payload.tcp_send) }
    }

    #[cfg(target_pointer_width = "32")]
    pub fn payload_write_to_file(&self) -> AnonStructBba21047290b1d3a {
        unsafe { core::ptr::read(self.payload.as_ptr() as *const AnonStructBba21047290b1d3a) }
    }

    #[cfg(not(target_pointer_width = "32"))]
    pub fn payload_write_to_file(&self) -> AnonStructBba21047290b1d3a {
        unsafe { core::mem::ManuallyDrop::into_inner(self.payload.write_to_file) }
    }

}

#[cfg(target_pointer_width = "64")]
const _: () = assert!(core::mem::size_of::<Effect>() == 56, "Effect size mismatch");
#[cfg(target_pointer_width = "64")]
const _: () = assert!(core::mem::align_of::<Effect>() == 8, "Effect alignment mismatch");
#[cfg(target_pointer_width = "64")]
const _: () = assert!(core::mem::offset_of!(Effect, tag) == 48, "Effect tag offset mismatch");
#[cfg(target_pointer_width = "32")]
const _: () = assert!(core::mem::size_of::<Effect>() == 32, "Effect size mismatch");
#[cfg(target_pointer_width = "32")]
const _: () = assert!(core::mem::align_of::<Effect>() == 8, "Effect alignment mismatch");
#[cfg(target_pointer_width = "32")]
const _: () = assert!(core::mem::offset_of!(Effect, tag) == 24, "Effect tag offset mismatch");

/// Tag discriminant for Try.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TryType24Tag {
    Err = 0,
    Ok = 1,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub union TryType24Payload {
    pub err: [u8; 0],
    pub ok: core::mem::ManuallyDrop<AnonStruct11c0d71a1110c7df>,
}

#[cfg(target_pointer_width = "32")]
#[repr(align(4))]
#[derive(Clone, Copy)]
pub struct TryType24PayloadAlignment;

/// Tag union: Try
#[cfg(target_pointer_width = "32")]
#[repr(C)]
#[derive(Clone, Copy)]
pub struct TryType24 {
    pub _payload_alignment: [TryType24PayloadAlignment; 0],
    pub payload: [u8; 24],
    pub tag: TryType24Tag,
}

/// Tag union: Try
#[cfg(not(target_pointer_width = "32"))]
#[repr(C)]
#[derive(Clone, Copy)]
pub struct TryType24 {
    pub payload: TryType24Payload,
    pub tag: TryType24Tag,
}

impl TryType24 {
    #[cfg(target_pointer_width = "32")]
    pub fn payload_ok(&self) -> AnonStruct11c0d71a1110c7df {
        unsafe { core::ptr::read(self.payload.as_ptr() as *const AnonStruct11c0d71a1110c7df) }
    }

    #[cfg(not(target_pointer_width = "32"))]
    pub fn payload_ok(&self) -> AnonStruct11c0d71a1110c7df {
        unsafe { core::mem::ManuallyDrop::into_inner(self.payload.ok) }
    }

}

#[cfg(target_pointer_width = "64")]
const _: () = assert!(core::mem::size_of::<TryType24>() == 56, "TryType24 size mismatch");
#[cfg(target_pointer_width = "64")]
const _: () = assert!(core::mem::align_of::<TryType24>() == 8, "TryType24 alignment mismatch");
#[cfg(target_pointer_width = "64")]
const _: () = assert!(core::mem::offset_of!(TryType24, tag) == 48, "TryType24 tag offset mismatch");
#[cfg(target_pointer_width = "32")]
const _: () = assert!(core::mem::size_of::<TryType24>() == 28, "TryType24 size mismatch");
#[cfg(target_pointer_width = "32")]
const _: () = assert!(core::mem::align_of::<TryType24>() == 4, "TryType24 alignment mismatch");
#[cfg(target_pointer_width = "32")]
const _: () = assert!(core::mem::offset_of!(TryType24, tag) == 24, "TryType24 tag offset mismatch");

/// Tag discriminant for Try.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TryType33Tag {
    Err = 0,
    Ok = 1,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub union TryType33Payload {
    pub err: [u8; 0],
    pub ok: core::mem::ManuallyDrop<RocErasedCallable>,
}

#[cfg(target_pointer_width = "32")]
#[repr(align(4))]
#[derive(Clone, Copy)]
pub struct TryType33PayloadAlignment;

/// Tag union: Try
#[cfg(target_pointer_width = "32")]
#[repr(C)]
#[derive(Clone, Copy)]
pub struct TryType33 {
    pub _payload_alignment: [TryType33PayloadAlignment; 0],
    pub payload: [u8; 4],
    pub tag: TryType33Tag,
}

/// Tag union: Try
#[cfg(not(target_pointer_width = "32"))]
#[repr(C)]
#[derive(Clone, Copy)]
pub struct TryType33 {
    pub payload: TryType33Payload,
    pub tag: TryType33Tag,
}

impl TryType33 {
    #[cfg(target_pointer_width = "32")]
    pub fn payload_ok(&self) -> RocErasedCallable {
        unsafe { core::ptr::read(self.payload.as_ptr() as *const RocErasedCallable) }
    }

    #[cfg(not(target_pointer_width = "32"))]
    pub fn payload_ok(&self) -> RocErasedCallable {
        unsafe { core::mem::ManuallyDrop::into_inner(self.payload.ok) }
    }

}

#[cfg(target_pointer_width = "64")]
const _: () = assert!(core::mem::size_of::<TryType33>() == 16, "TryType33 size mismatch");
#[cfg(target_pointer_width = "64")]
const _: () = assert!(core::mem::align_of::<TryType33>() == 8, "TryType33 alignment mismatch");
#[cfg(target_pointer_width = "64")]
const _: () = assert!(core::mem::offset_of!(TryType33, tag) == 8, "TryType33 tag offset mismatch");
#[cfg(target_pointer_width = "32")]
const _: () = assert!(core::mem::size_of::<TryType33>() == 8, "TryType33 size mismatch");
#[cfg(target_pointer_width = "32")]
const _: () = assert!(core::mem::align_of::<TryType33>() == 4, "TryType33 alignment mismatch");
#[cfg(target_pointer_width = "32")]
const _: () = assert!(core::mem::offset_of!(TryType33, tag) == 4, "TryType33 tag offset mismatch");

/// Tag discriminant for ANSI.Input.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ANSIInputTag {
    Action = 0,
    Arrow = 1,
    Ctrl = 2,
    Lower = 3,
    Number = 4,
    Symbol = 5,
    Unsupported = 6,
    Upper = 7,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub union ANSIInputPayload {
    pub action: core::mem::ManuallyDrop<ANSIAction>,
    pub arrow: core::mem::ManuallyDrop<ANSIArrow>,
    pub ctrl: core::mem::ManuallyDrop<ANSICtrl>,
    pub lower: core::mem::ManuallyDrop<ANSILetter>,
    pub number: core::mem::ManuallyDrop<ANSINumber>,
    pub symbol: core::mem::ManuallyDrop<ANSISymbol>,
    pub unsupported: core::mem::ManuallyDrop<RocListWith<u8, false>>,
    pub upper: core::mem::ManuallyDrop<ANSILetter>,
}

#[cfg(target_pointer_width = "32")]
#[repr(align(4))]
#[derive(Clone, Copy)]
pub struct ANSIInputPayloadAlignment;

/// Tag union: ANSI.Input
#[cfg(target_pointer_width = "32")]
#[repr(C)]
#[derive(Clone, Copy)]
pub struct ANSIInput {
    pub _payload_alignment: [ANSIInputPayloadAlignment; 0],
    pub payload: [u8; 12],
    pub tag: ANSIInputTag,
}

/// Tag union: ANSI.Input
#[cfg(not(target_pointer_width = "32"))]
#[repr(C)]
#[derive(Clone, Copy)]
pub struct ANSIInput {
    pub payload: ANSIInputPayload,
    pub tag: ANSIInputTag,
}

impl ANSIInput {
    #[cfg(target_pointer_width = "32")]
    pub fn payload_action(&self) -> ANSIAction {
        unsafe { core::ptr::read(self.payload.as_ptr() as *const ANSIAction) }
    }

    #[cfg(not(target_pointer_width = "32"))]
    pub fn payload_action(&self) -> ANSIAction {
        unsafe { core::mem::ManuallyDrop::into_inner(self.payload.action) }
    }

    #[cfg(target_pointer_width = "32")]
    pub fn payload_arrow(&self) -> ANSIArrow {
        unsafe { core::ptr::read(self.payload.as_ptr() as *const ANSIArrow) }
    }

    #[cfg(not(target_pointer_width = "32"))]
    pub fn payload_arrow(&self) -> ANSIArrow {
        unsafe { core::mem::ManuallyDrop::into_inner(self.payload.arrow) }
    }

    #[cfg(target_pointer_width = "32")]
    pub fn payload_ctrl(&self) -> ANSICtrl {
        unsafe { core::ptr::read(self.payload.as_ptr() as *const ANSICtrl) }
    }

    #[cfg(not(target_pointer_width = "32"))]
    pub fn payload_ctrl(&self) -> ANSICtrl {
        unsafe { core::mem::ManuallyDrop::into_inner(self.payload.ctrl) }
    }

    #[cfg(target_pointer_width = "32")]
    pub fn payload_lower(&self) -> ANSILetter {
        unsafe { core::ptr::read(self.payload.as_ptr() as *const ANSILetter) }
    }

    #[cfg(not(target_pointer_width = "32"))]
    pub fn payload_lower(&self) -> ANSILetter {
        unsafe { core::mem::ManuallyDrop::into_inner(self.payload.lower) }
    }

    #[cfg(target_pointer_width = "32")]
    pub fn payload_number(&self) -> ANSINumber {
        unsafe { core::ptr::read(self.payload.as_ptr() as *const ANSINumber) }
    }

    #[cfg(not(target_pointer_width = "32"))]
    pub fn payload_number(&self) -> ANSINumber {
        unsafe { core::mem::ManuallyDrop::into_inner(self.payload.number) }
    }

    #[cfg(target_pointer_width = "32")]
    pub fn payload_symbol(&self) -> ANSISymbol {
        unsafe { core::ptr::read(self.payload.as_ptr() as *const ANSISymbol) }
    }

    #[cfg(not(target_pointer_width = "32"))]
    pub fn payload_symbol(&self) -> ANSISymbol {
        unsafe { core::mem::ManuallyDrop::into_inner(self.payload.symbol) }
    }

    #[cfg(target_pointer_width = "32")]
    pub fn payload_unsupported(&self) -> RocListWith<u8, false> {
        unsafe { core::ptr::read(self.payload.as_ptr() as *const RocListWith<u8, false>) }
    }

    #[cfg(not(target_pointer_width = "32"))]
    pub fn payload_unsupported(&self) -> RocListWith<u8, false> {
        unsafe { core::mem::ManuallyDrop::into_inner(self.payload.unsupported) }
    }

    #[cfg(target_pointer_width = "32")]
    pub fn payload_upper(&self) -> ANSILetter {
        unsafe { core::ptr::read(self.payload.as_ptr() as *const ANSILetter) }
    }

    #[cfg(not(target_pointer_width = "32"))]
    pub fn payload_upper(&self) -> ANSILetter {
        unsafe { core::mem::ManuallyDrop::into_inner(self.payload.upper) }
    }

}

#[cfg(target_pointer_width = "64")]
const _: () = assert!(core::mem::size_of::<ANSIInput>() == 32, "ANSIInput size mismatch");
#[cfg(target_pointer_width = "64")]
const _: () = assert!(core::mem::align_of::<ANSIInput>() == 8, "ANSIInput alignment mismatch");
#[cfg(target_pointer_width = "64")]
const _: () = assert!(core::mem::offset_of!(ANSIInput, tag) == 24, "ANSIInput tag offset mismatch");
#[cfg(target_pointer_width = "32")]
const _: () = assert!(core::mem::size_of::<ANSIInput>() == 16, "ANSIInput size mismatch");
#[cfg(target_pointer_width = "32")]
const _: () = assert!(core::mem::align_of::<ANSIInput>() == 4, "ANSIInput alignment mismatch");
#[cfg(target_pointer_width = "32")]
const _: () = assert!(core::mem::offset_of!(ANSIInput, tag) == 12, "ANSIInput tag offset mismatch");

/// Tag union: ANSI.Action
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ANSIAction {
    Delete = 0,
    Enter = 1,
    Escape = 2,
    Space = 3,
}

#[cfg(target_pointer_width = "64")]
const _: () = assert!(core::mem::size_of::<ANSIAction>() == 1, "ANSIAction size mismatch");
#[cfg(target_pointer_width = "64")]
const _: () = assert!(core::mem::align_of::<ANSIAction>() == 1, "ANSIAction alignment mismatch");
#[cfg(target_pointer_width = "32")]
const _: () = assert!(core::mem::size_of::<ANSIAction>() == 1, "ANSIAction size mismatch");
#[cfg(target_pointer_width = "32")]
const _: () = assert!(core::mem::align_of::<ANSIAction>() == 1, "ANSIAction alignment mismatch");

/// Tag union: ANSI.Arrow
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ANSIArrow {
    Down = 0,
    Left = 1,
    Right = 2,
    Up = 3,
}

#[cfg(target_pointer_width = "64")]
const _: () = assert!(core::mem::size_of::<ANSIArrow>() == 1, "ANSIArrow size mismatch");
#[cfg(target_pointer_width = "64")]
const _: () = assert!(core::mem::align_of::<ANSIArrow>() == 1, "ANSIArrow alignment mismatch");
#[cfg(target_pointer_width = "32")]
const _: () = assert!(core::mem::size_of::<ANSIArrow>() == 1, "ANSIArrow size mismatch");
#[cfg(target_pointer_width = "32")]
const _: () = assert!(core::mem::align_of::<ANSIArrow>() == 1, "ANSIArrow alignment mismatch");

/// Tag union: ANSI.Ctrl
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ANSICtrl {
    A = 0,
    B = 1,
    BackSlash = 2,
    C = 3,
    Caret = 4,
    D = 5,
    E = 6,
    F = 7,
    G = 8,
    H = 9,
    I = 10,
    J = 11,
    K = 12,
    L = 13,
    N = 14,
    O = 15,
    P = 16,
    Q = 17,
    R = 18,
    S = 19,
    Space = 20,
    SquareCloseBracket = 21,
    T = 22,
    U = 23,
    Underscore = 24,
    V = 25,
    W = 26,
    X = 27,
    Y = 28,
    Z = 29,
}

#[cfg(target_pointer_width = "64")]
const _: () = assert!(core::mem::size_of::<ANSICtrl>() == 1, "ANSICtrl size mismatch");
#[cfg(target_pointer_width = "64")]
const _: () = assert!(core::mem::align_of::<ANSICtrl>() == 1, "ANSICtrl alignment mismatch");
#[cfg(target_pointer_width = "32")]
const _: () = assert!(core::mem::size_of::<ANSICtrl>() == 1, "ANSICtrl size mismatch");
#[cfg(target_pointer_width = "32")]
const _: () = assert!(core::mem::align_of::<ANSICtrl>() == 1, "ANSICtrl alignment mismatch");

/// Tag union: ANSI.Letter
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ANSILetter {
    A = 0,
    B = 1,
    C = 2,
    D = 3,
    E = 4,
    F = 5,
    G = 6,
    H = 7,
    I = 8,
    J = 9,
    K = 10,
    L = 11,
    M = 12,
    N = 13,
    O = 14,
    P = 15,
    Q = 16,
    R = 17,
    S = 18,
    T = 19,
    U = 20,
    V = 21,
    W = 22,
    X = 23,
    Y = 24,
    Z = 25,
}

#[cfg(target_pointer_width = "64")]
const _: () = assert!(core::mem::size_of::<ANSILetter>() == 1, "ANSILetter size mismatch");
#[cfg(target_pointer_width = "64")]
const _: () = assert!(core::mem::align_of::<ANSILetter>() == 1, "ANSILetter alignment mismatch");
#[cfg(target_pointer_width = "32")]
const _: () = assert!(core::mem::size_of::<ANSILetter>() == 1, "ANSILetter size mismatch");
#[cfg(target_pointer_width = "32")]
const _: () = assert!(core::mem::align_of::<ANSILetter>() == 1, "ANSILetter alignment mismatch");

/// Tag union: ANSI.Number
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ANSINumber {
    N0 = 0,
    N1 = 1,
    N2 = 2,
    N3 = 3,
    N4 = 4,
    N5 = 5,
    N6 = 6,
    N7 = 7,
    N8 = 8,
    N9 = 9,
}

#[cfg(target_pointer_width = "64")]
const _: () = assert!(core::mem::size_of::<ANSINumber>() == 1, "ANSINumber size mismatch");
#[cfg(target_pointer_width = "64")]
const _: () = assert!(core::mem::align_of::<ANSINumber>() == 1, "ANSINumber alignment mismatch");
#[cfg(target_pointer_width = "32")]
const _: () = assert!(core::mem::size_of::<ANSINumber>() == 1, "ANSINumber size mismatch");
#[cfg(target_pointer_width = "32")]
const _: () = assert!(core::mem::align_of::<ANSINumber>() == 1, "ANSINumber alignment mismatch");

/// Tag union: ANSI.Symbol
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ANSISymbol {
    Ampersand = 0,
    Apostrophe = 1,
    Asterisk = 2,
    AtSign = 3,
    Backslash = 4,
    Caret = 5,
    Colon = 6,
    Comma = 7,
    CurlyCloseBrace = 8,
    CurlyOpenBrace = 9,
    DollarSign = 10,
    EqualsSign = 11,
    ExclamationMark = 12,
    ForwardSlash = 13,
    FullStop = 14,
    GraveAccent = 15,
    GreaterThanSign = 16,
    Hyphen = 17,
    LessThanSign = 18,
    NumberSign = 19,
    PercentSign = 20,
    PlusSign = 21,
    QuestionMark = 22,
    QuotationMark = 23,
    RoundCloseBracket = 24,
    RoundOpenBracket = 25,
    SemiColon = 26,
    SquareCloseBracket = 27,
    SquareOpenBracket = 28,
    Tilde = 29,
    Underscore = 30,
    VerticalBar = 31,
}

#[cfg(target_pointer_width = "64")]
const _: () = assert!(core::mem::size_of::<ANSISymbol>() == 1, "ANSISymbol size mismatch");
#[cfg(target_pointer_width = "64")]
const _: () = assert!(core::mem::align_of::<ANSISymbol>() == 1, "ANSISymbol alignment mismatch");
#[cfg(target_pointer_width = "32")]
const _: () = assert!(core::mem::size_of::<ANSISymbol>() == 1, "ANSISymbol size mismatch");
#[cfg(target_pointer_width = "32")]
const _: () = assert!(core::mem::align_of::<ANSISymbol>() == 1, "ANSISymbol alignment mismatch");

/// Tag discriminant for Try.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TryType47Tag {
    Err = 0,
    Ok = 1,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub union TryType47Payload {
    pub err: [u8; 0],
    pub ok: core::mem::ManuallyDrop<AnonStruct3662079be59957c3>,
}

#[cfg(target_pointer_width = "32")]
#[repr(align(4))]
#[derive(Clone, Copy)]
pub struct TryType47PayloadAlignment;

/// Tag union: Try
#[cfg(target_pointer_width = "32")]
#[repr(C)]
#[derive(Clone, Copy)]
pub struct TryType47 {
    pub _payload_alignment: [TryType47PayloadAlignment; 0],
    pub payload: [u8; 24],
    pub tag: TryType47Tag,
}

/// Tag union: Try
#[cfg(not(target_pointer_width = "32"))]
#[repr(C)]
#[derive(Clone, Copy)]
pub struct TryType47 {
    pub payload: TryType47Payload,
    pub tag: TryType47Tag,
}

impl TryType47 {
    #[cfg(target_pointer_width = "32")]
    pub fn payload_ok(&self) -> AnonStruct3662079be59957c3 {
        unsafe { core::ptr::read(self.payload.as_ptr() as *const AnonStruct3662079be59957c3) }
    }

    #[cfg(not(target_pointer_width = "32"))]
    pub fn payload_ok(&self) -> AnonStruct3662079be59957c3 {
        unsafe { core::mem::ManuallyDrop::into_inner(self.payload.ok) }
    }

}

#[cfg(target_pointer_width = "64")]
const _: () = assert!(core::mem::size_of::<TryType47>() == 56, "TryType47 size mismatch");
#[cfg(target_pointer_width = "64")]
const _: () = assert!(core::mem::align_of::<TryType47>() == 8, "TryType47 alignment mismatch");
#[cfg(target_pointer_width = "64")]
const _: () = assert!(core::mem::offset_of!(TryType47, tag) == 48, "TryType47 tag offset mismatch");
#[cfg(target_pointer_width = "32")]
const _: () = assert!(core::mem::size_of::<TryType47>() == 28, "TryType47 size mismatch");
#[cfg(target_pointer_width = "32")]
const _: () = assert!(core::mem::align_of::<TryType47>() == 4, "TryType47 alignment mismatch");
#[cfg(target_pointer_width = "32")]
const _: () = assert!(core::mem::offset_of!(TryType47, tag) == 24, "TryType47 tag offset mismatch");

/// Tag discriminant for Try.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TryType56Tag {
    Err = 0,
    Ok = 1,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub union TryType56Payload {
    pub err: [u8; 0],
    pub ok: core::mem::ManuallyDrop<RocErasedCallable>,
}

#[cfg(target_pointer_width = "32")]
#[repr(align(4))]
#[derive(Clone, Copy)]
pub struct TryType56PayloadAlignment;

/// Tag union: Try
#[cfg(target_pointer_width = "32")]
#[repr(C)]
#[derive(Clone, Copy)]
pub struct TryType56 {
    pub _payload_alignment: [TryType56PayloadAlignment; 0],
    pub payload: [u8; 4],
    pub tag: TryType56Tag,
}

/// Tag union: Try
#[cfg(not(target_pointer_width = "32"))]
#[repr(C)]
#[derive(Clone, Copy)]
pub struct TryType56 {
    pub payload: TryType56Payload,
    pub tag: TryType56Tag,
}

impl TryType56 {
    #[cfg(target_pointer_width = "32")]
    pub fn payload_ok(&self) -> RocErasedCallable {
        unsafe { core::ptr::read(self.payload.as_ptr() as *const RocErasedCallable) }
    }

    #[cfg(not(target_pointer_width = "32"))]
    pub fn payload_ok(&self) -> RocErasedCallable {
        unsafe { core::mem::ManuallyDrop::into_inner(self.payload.ok) }
    }

}

#[cfg(target_pointer_width = "64")]
const _: () = assert!(core::mem::size_of::<TryType56>() == 16, "TryType56 size mismatch");
#[cfg(target_pointer_width = "64")]
const _: () = assert!(core::mem::align_of::<TryType56>() == 8, "TryType56 alignment mismatch");
#[cfg(target_pointer_width = "64")]
const _: () = assert!(core::mem::offset_of!(TryType56, tag) == 8, "TryType56 tag offset mismatch");
#[cfg(target_pointer_width = "32")]
const _: () = assert!(core::mem::size_of::<TryType56>() == 8, "TryType56 size mismatch");
#[cfg(target_pointer_width = "32")]
const _: () = assert!(core::mem::align_of::<TryType56>() == 4, "TryType56 alignment mismatch");
#[cfg(target_pointer_width = "32")]
const _: () = assert!(core::mem::offset_of!(TryType56, tag) == 4, "TryType56 tag offset mismatch");

/// Tag discriminant for Try.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ViewForHostResultTag {
    Err = 0,
    Ok = 1,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub union ViewForHostResultPayload {
    pub err: [u8; 0],
    pub ok: core::mem::ManuallyDrop<RocList<RocStr>>,
}

#[cfg(target_pointer_width = "32")]
#[repr(align(4))]
#[derive(Clone, Copy)]
pub struct ViewForHostResultPayloadAlignment;

/// Tag union: Try
#[cfg(target_pointer_width = "32")]
#[repr(C)]
#[derive(Clone, Copy)]
pub struct ViewForHostResult {
    pub _payload_alignment: [ViewForHostResultPayloadAlignment; 0],
    pub payload: [u8; 12],
    pub tag: ViewForHostResultTag,
}

/// Tag union: Try
#[cfg(not(target_pointer_width = "32"))]
#[repr(C)]
#[derive(Clone, Copy)]
pub struct ViewForHostResult {
    pub payload: ViewForHostResultPayload,
    pub tag: ViewForHostResultTag,
}

impl ViewForHostResult {
    #[cfg(target_pointer_width = "32")]
    pub fn payload_ok(&self) -> RocList<RocStr> {
        unsafe { core::ptr::read(self.payload.as_ptr() as *const RocList<RocStr>) }
    }

    #[cfg(not(target_pointer_width = "32"))]
    pub fn payload_ok(&self) -> RocList<RocStr> {
        unsafe { core::mem::ManuallyDrop::into_inner(self.payload.ok) }
    }

}

#[cfg(target_pointer_width = "64")]
const _: () = assert!(core::mem::size_of::<ViewForHostResult>() == 32, "ViewForHostResult size mismatch");
#[cfg(target_pointer_width = "64")]
const _: () = assert!(core::mem::align_of::<ViewForHostResult>() == 8, "ViewForHostResult alignment mismatch");
#[cfg(target_pointer_width = "64")]
const _: () = assert!(core::mem::offset_of!(ViewForHostResult, tag) == 24, "ViewForHostResult tag offset mismatch");
#[cfg(target_pointer_width = "32")]
const _: () = assert!(core::mem::size_of::<ViewForHostResult>() == 16, "ViewForHostResult size mismatch");
#[cfg(target_pointer_width = "32")]
const _: () = assert!(core::mem::align_of::<ViewForHostResult>() == 4, "ViewForHostResult alignment mismatch");
#[cfg(target_pointer_width = "32")]
const _: () = assert!(core::mem::offset_of!(ViewForHostResult, tag) == 12, "ViewForHostResult tag offset mismatch");

// Platform Type Aliases

pub type InitForHost = AnonStruct3a8854a0aa6a1ebb;
pub type InitForHostEffects = Effect;
pub type InitForHostEffectsPayload = EffectPayload;
pub type InitForHostEffectsTag = EffectTag;
pub type InitForHostEffectsTcpSend = AnonStruct3b1714e0f1aad535;
pub type InitForHostEffectsWriteToFile = AnonStructBba21047290b1d3a;
pub type EffectTcpSend = AnonStruct3b1714e0f1aad535;
pub type EffectWriteToFile = AnonStructBba21047290b1d3a;
pub type SubscriptionsAcceptTcpConnectionResult = TryType24;
pub type SubscriptionsAcceptTcpConnectionResultPayload = TryType24Payload;
pub type SubscriptionsAcceptTcpConnectionResultTag = TryType24Tag;
pub type SubscriptionsAcceptTcpConnectionOk = AnonStruct11c0d71a1110c7df;
pub type SubscriptionsStdinResult = TryType33;
pub type SubscriptionsStdinResultPayload = TryType33Payload;
pub type SubscriptionsStdinResultTag = TryType33Tag;
pub type SubscriptionsTcpConnectResult = TryType47;
pub type SubscriptionsTcpConnectResultPayload = TryType47Payload;
pub type SubscriptionsTcpConnectResultTag = TryType47Tag;
pub type SubscriptionsTcpConnectOk = AnonStruct3662079be59957c3;
pub type SubscriptionsTcpReceiveResult = TryType56;
pub type SubscriptionsTcpReceiveResultPayload = TryType56Payload;
pub type SubscriptionsTcpReceiveResultTag = TryType56Tag;
pub type UpdateForHost = AnonStruct3a8854a0aa6a1ebb;
pub type UpdateForHostEffects = Effect;
pub type UpdateForHostEffectsPayload = EffectPayload;
pub type UpdateForHostEffectsTag = EffectTag;
pub type UpdateForHostEffectsTcpSend = AnonStruct3b1714e0f1aad535;
pub type UpdateForHostEffectsWriteToFile = AnonStructBba21047290b1d3a;

// Generated Refcount Helpers

impl AnonStruct57e411f048803101 {
    /// Recursively decrement Roc-owned fields.
    ///
    /// # Safety
    /// `self` must own one live Roc reference for each refcounted field.
    pub unsafe fn decref(self, roc_host: &RocHost) {
        let value = self;
        let _ = value;
        let _ = roc_host;
    }

    /// Increment Roc-owned fields.
    ///
    /// # Safety
    /// `self` must point at live Roc allocations. The retained references must
    /// be balanced by later decrefs.
    pub unsafe fn incref(self, amount: isize) {
        let value = self;
        let _ = value;
        let _ = amount;
    }
}

impl AnonStruct3a8854a0aa6a1ebb {
    /// Recursively decrement Roc-owned fields.
    ///
    /// # Safety
    /// `self` must own one live Roc reference for each refcounted field.
    pub unsafe fn decref(self, roc_host: &RocHost) {
        let value = self;
        {
            let list = value.effects;
            if list.has_one_ref() {
                for item_ref in list.allocation_items() {
                    let item = *item_ref;
                        unsafe { item.decref(roc_host); }
                }
            }
            unsafe { list.decref(roc_host); }
        }
        unsafe { decref_box(value.m as RocBox, roc_host); }
        unsafe { value.sub.decref(roc_host); }
    }

    /// Increment Roc-owned fields.
    ///
    /// # Safety
    /// `self` must point at live Roc allocations. The retained references must
    /// be balanced by later decrefs.
    pub unsafe fn incref(self, amount: isize) {
        let value = self;
        unsafe { value.effects.incref(amount); }
        unsafe { incref_box(value.m as RocBox, amount); }
        unsafe { value.sub.incref(amount); }
    }
}

impl Effect {
    /// Recursively decrement Roc-owned payloads.
    ///
    /// # Safety
    /// `self` must own one live Roc reference for each refcounted payload.
    pub unsafe fn decref(self, roc_host: &RocHost) {
        let value = self;
        let _ = roc_host;
        match value.tag {
            EffectTag::Exit => {},
            EffectTag::Print => {
                let payload = value.payload_print();
                unsafe { payload.decref(roc_host); }
            },
            EffectTag::TcpSend => {
                let payload = value.payload_tcp_send();
                unsafe { payload.decref(roc_host); }
            },
            EffectTag::WriteToFile => {
                let payload = value.payload_write_to_file();
                unsafe { payload.decref(roc_host); }
            },
        }
    }

    /// Increment Roc-owned payloads.
    ///
    /// # Safety
    /// `self` must point at live Roc allocations. The retained references must
    /// be balanced by later decrefs.
    pub unsafe fn incref(self, amount: isize) {
        let value = self;
        let _ = amount;
        match value.tag {
            EffectTag::Exit => {},
            EffectTag::Print => {
                let payload = value.payload_print();
                unsafe { payload.incref(amount); }
            },
            EffectTag::TcpSend => {
                let payload = value.payload_tcp_send();
                unsafe { payload.incref(amount); }
            },
            EffectTag::WriteToFile => {
                let payload = value.payload_write_to_file();
                unsafe { payload.incref(amount); }
            },
        }
    }
}

impl AnonStruct3b1714e0f1aad535 {
    /// Recursively decrement Roc-owned fields.
    ///
    /// # Safety
    /// `self` must own one live Roc reference for each refcounted field.
    pub unsafe fn decref(self, roc_host: &RocHost) {
        let value = self;
        unsafe { value.stream.decref(roc_host); }
        unsafe { value.data.decref(roc_host); }
    }

    /// Increment Roc-owned fields.
    ///
    /// # Safety
    /// `self` must point at live Roc allocations. The retained references must
    /// be balanced by later decrefs.
    pub unsafe fn incref(self, amount: isize) {
        let value = self;
        unsafe { value.stream.incref(amount); }
        unsafe { value.data.incref(amount); }
    }
}

impl TcpStream {
    /// Recursively decrement Roc-owned fields.
    ///
    /// # Safety
    /// `self` must own one live Roc reference for each refcounted field.
    pub unsafe fn decref(self, roc_host: &RocHost) {
        let value = self;
        let _ = value;
        let _ = roc_host;
    }

    /// Increment Roc-owned fields.
    ///
    /// # Safety
    /// `self` must point at live Roc allocations. The retained references must
    /// be balanced by later decrefs.
    pub unsafe fn incref(self, amount: isize) {
        let value = self;
        let _ = value;
        let _ = amount;
    }
}

impl AnonStructBba21047290b1d3a {
    /// Recursively decrement Roc-owned fields.
    ///
    /// # Safety
    /// `self` must own one live Roc reference for each refcounted field.
    pub unsafe fn decref(self, roc_host: &RocHost) {
        let value = self;
        unsafe { value.content.decref(roc_host); }
        unsafe { value.filename.decref(roc_host); }
    }

    /// Increment Roc-owned fields.
    ///
    /// # Safety
    /// `self` must point at live Roc allocations. The retained references must
    /// be balanced by later decrefs.
    pub unsafe fn incref(self, amount: isize) {
        let value = self;
        unsafe { value.content.incref(amount); }
        unsafe { value.filename.incref(amount); }
    }
}

impl Subscriptions {
    /// Recursively decrement Roc-owned fields.
    ///
    /// # Safety
    /// `self` must own one live Roc reference for each refcounted field.
    pub unsafe fn decref(self, roc_host: &RocHost) {
        let value = self;
        unsafe { value.accept_tcp_connection.decref(roc_host); }
        unsafe { value.stdin.decref(roc_host); }
        unsafe { value.tcp_connect.decref(roc_host); }
        unsafe { value.tcp_receive.decref(roc_host); }
    }

    /// Increment Roc-owned fields.
    ///
    /// # Safety
    /// `self` must point at live Roc allocations. The retained references must
    /// be balanced by later decrefs.
    pub unsafe fn incref(self, amount: isize) {
        let value = self;
        unsafe { value.accept_tcp_connection.incref(amount); }
        unsafe { value.stdin.incref(amount); }
        unsafe { value.tcp_connect.incref(amount); }
        unsafe { value.tcp_receive.incref(amount); }
    }
}

impl TryType24 {
    /// Recursively decrement Roc-owned payloads.
    ///
    /// # Safety
    /// `self` must own one live Roc reference for each refcounted payload.
    pub unsafe fn decref(self, roc_host: &RocHost) {
        let value = self;
        let _ = roc_host;
        match value.tag {
            TryType24Tag::Err => {},
            TryType24Tag::Ok => {
                let payload = value.payload_ok();
                unsafe { payload.decref(roc_host); }
            },
        }
    }

    /// Increment Roc-owned payloads.
    ///
    /// # Safety
    /// `self` must point at live Roc allocations. The retained references must
    /// be balanced by later decrefs.
    pub unsafe fn incref(self, amount: isize) {
        let value = self;
        let _ = amount;
        match value.tag {
            TryType24Tag::Err => {},
            TryType24Tag::Ok => {
                let payload = value.payload_ok();
                unsafe { payload.incref(amount); }
            },
        }
    }
}

impl AnonStruct11c0d71a1110c7df {
    /// Recursively decrement Roc-owned fields.
    ///
    /// # Safety
    /// `self` must own one live Roc reference for each refcounted field.
    pub unsafe fn decref(self, roc_host: &RocHost) {
        let value = self;
        unsafe { value.host.decref(roc_host); }
        unsafe { decref_erased_callable(value.on_connected, roc_host); }
        unsafe { decref_erased_callable(value.on_disconnected, roc_host); }
    }

    /// Increment Roc-owned fields.
    ///
    /// # Safety
    /// `self` must point at live Roc allocations. The retained references must
    /// be balanced by later decrefs.
    pub unsafe fn incref(self, amount: isize) {
        let value = self;
        unsafe { value.host.incref(amount); }
        unsafe { incref_erased_callable(value.on_connected, amount); }
        unsafe { incref_erased_callable(value.on_disconnected, amount); }
    }
}

impl TryType33 {
    /// Recursively decrement Roc-owned payloads.
    ///
    /// # Safety
    /// `self` must own one live Roc reference for each refcounted payload.
    pub unsafe fn decref(self, roc_host: &RocHost) {
        let value = self;
        let _ = roc_host;
        match value.tag {
            TryType33Tag::Err => {},
            TryType33Tag::Ok => {
                let payload = value.payload_ok();
                unsafe { decref_erased_callable(payload, roc_host); }
            },
        }
    }

    /// Increment Roc-owned payloads.
    ///
    /// # Safety
    /// `self` must point at live Roc allocations. The retained references must
    /// be balanced by later decrefs.
    pub unsafe fn incref(self, amount: isize) {
        let value = self;
        let _ = amount;
        match value.tag {
            TryType33Tag::Err => {},
            TryType33Tag::Ok => {
                let payload = value.payload_ok();
                unsafe { incref_erased_callable(payload, amount); }
            },
        }
    }
}

impl ANSIInput {
    /// Recursively decrement Roc-owned payloads.
    ///
    /// # Safety
    /// `self` must own one live Roc reference for each refcounted payload.
    pub unsafe fn decref(self, roc_host: &RocHost) {
        let value = self;
        let _ = roc_host;
        match value.tag {
            ANSIInputTag::Action => {
                let payload = value.payload_action();
                unsafe { payload.decref(roc_host); }
            },
            ANSIInputTag::Arrow => {
                let payload = value.payload_arrow();
                unsafe { payload.decref(roc_host); }
            },
            ANSIInputTag::Ctrl => {
                let payload = value.payload_ctrl();
                unsafe { payload.decref(roc_host); }
            },
            ANSIInputTag::Lower => {
                let payload = value.payload_lower();
                unsafe { payload.decref(roc_host); }
            },
            ANSIInputTag::Number => {
                let payload = value.payload_number();
                unsafe { payload.decref(roc_host); }
            },
            ANSIInputTag::Symbol => {
                let payload = value.payload_symbol();
                unsafe { payload.decref(roc_host); }
            },
            ANSIInputTag::Unsupported => {
                let payload = value.payload_unsupported();
                unsafe { payload.decref(roc_host); }
            },
            ANSIInputTag::Upper => {
                let payload = value.payload_upper();
                unsafe { payload.decref(roc_host); }
            },
        }
    }

    /// Increment Roc-owned payloads.
    ///
    /// # Safety
    /// `self` must point at live Roc allocations. The retained references must
    /// be balanced by later decrefs.
    pub unsafe fn incref(self, amount: isize) {
        let value = self;
        let _ = amount;
        match value.tag {
            ANSIInputTag::Action => {
                let payload = value.payload_action();
                unsafe { payload.incref(amount); }
            },
            ANSIInputTag::Arrow => {
                let payload = value.payload_arrow();
                unsafe { payload.incref(amount); }
            },
            ANSIInputTag::Ctrl => {
                let payload = value.payload_ctrl();
                unsafe { payload.incref(amount); }
            },
            ANSIInputTag::Lower => {
                let payload = value.payload_lower();
                unsafe { payload.incref(amount); }
            },
            ANSIInputTag::Number => {
                let payload = value.payload_number();
                unsafe { payload.incref(amount); }
            },
            ANSIInputTag::Symbol => {
                let payload = value.payload_symbol();
                unsafe { payload.incref(amount); }
            },
            ANSIInputTag::Unsupported => {
                let payload = value.payload_unsupported();
                unsafe { payload.incref(amount); }
            },
            ANSIInputTag::Upper => {
                let payload = value.payload_upper();
                unsafe { payload.incref(amount); }
            },
        }
    }
}

impl ANSIAction {
    /// Recursively decrement Roc-owned payloads.
    ///
    /// # Safety
    /// `self` must own one live Roc reference for each refcounted payload.
    pub unsafe fn decref(self, roc_host: &RocHost) {
        let _ = self;
        let _ = roc_host;
    }

    /// Increment Roc-owned payloads.
    ///
    /// # Safety
    /// `self` must point at live Roc allocations. The retained references must
    /// be balanced by later decrefs.
    pub unsafe fn incref(self, amount: isize) {
        let _ = self;
        let _ = amount;
    }
}

impl ANSIArrow {
    /// Recursively decrement Roc-owned payloads.
    ///
    /// # Safety
    /// `self` must own one live Roc reference for each refcounted payload.
    pub unsafe fn decref(self, roc_host: &RocHost) {
        let _ = self;
        let _ = roc_host;
    }

    /// Increment Roc-owned payloads.
    ///
    /// # Safety
    /// `self` must point at live Roc allocations. The retained references must
    /// be balanced by later decrefs.
    pub unsafe fn incref(self, amount: isize) {
        let _ = self;
        let _ = amount;
    }
}

impl ANSICtrl {
    /// Recursively decrement Roc-owned payloads.
    ///
    /// # Safety
    /// `self` must own one live Roc reference for each refcounted payload.
    pub unsafe fn decref(self, roc_host: &RocHost) {
        let _ = self;
        let _ = roc_host;
    }

    /// Increment Roc-owned payloads.
    ///
    /// # Safety
    /// `self` must point at live Roc allocations. The retained references must
    /// be balanced by later decrefs.
    pub unsafe fn incref(self, amount: isize) {
        let _ = self;
        let _ = amount;
    }
}

impl ANSILetter {
    /// Recursively decrement Roc-owned payloads.
    ///
    /// # Safety
    /// `self` must own one live Roc reference for each refcounted payload.
    pub unsafe fn decref(self, roc_host: &RocHost) {
        let _ = self;
        let _ = roc_host;
    }

    /// Increment Roc-owned payloads.
    ///
    /// # Safety
    /// `self` must point at live Roc allocations. The retained references must
    /// be balanced by later decrefs.
    pub unsafe fn incref(self, amount: isize) {
        let _ = self;
        let _ = amount;
    }
}

impl ANSINumber {
    /// Recursively decrement Roc-owned payloads.
    ///
    /// # Safety
    /// `self` must own one live Roc reference for each refcounted payload.
    pub unsafe fn decref(self, roc_host: &RocHost) {
        let _ = self;
        let _ = roc_host;
    }

    /// Increment Roc-owned payloads.
    ///
    /// # Safety
    /// `self` must point at live Roc allocations. The retained references must
    /// be balanced by later decrefs.
    pub unsafe fn incref(self, amount: isize) {
        let _ = self;
        let _ = amount;
    }
}

impl ANSISymbol {
    /// Recursively decrement Roc-owned payloads.
    ///
    /// # Safety
    /// `self` must own one live Roc reference for each refcounted payload.
    pub unsafe fn decref(self, roc_host: &RocHost) {
        let _ = self;
        let _ = roc_host;
    }

    /// Increment Roc-owned payloads.
    ///
    /// # Safety
    /// `self` must point at live Roc allocations. The retained references must
    /// be balanced by later decrefs.
    pub unsafe fn incref(self, amount: isize) {
        let _ = self;
        let _ = amount;
    }
}

impl TryType47 {
    /// Recursively decrement Roc-owned payloads.
    ///
    /// # Safety
    /// `self` must own one live Roc reference for each refcounted payload.
    pub unsafe fn decref(self, roc_host: &RocHost) {
        let value = self;
        let _ = roc_host;
        match value.tag {
            TryType47Tag::Err => {},
            TryType47Tag::Ok => {
                let payload = value.payload_ok();
                unsafe { payload.decref(roc_host); }
            },
        }
    }

    /// Increment Roc-owned payloads.
    ///
    /// # Safety
    /// `self` must point at live Roc allocations. The retained references must
    /// be balanced by later decrefs.
    pub unsafe fn incref(self, amount: isize) {
        let value = self;
        let _ = amount;
        match value.tag {
            TryType47Tag::Err => {},
            TryType47Tag::Ok => {
                let payload = value.payload_ok();
                unsafe { payload.incref(amount); }
            },
        }
    }
}

impl AnonStruct3662079be59957c3 {
    /// Recursively decrement Roc-owned fields.
    ///
    /// # Safety
    /// `self` must own one live Roc reference for each refcounted field.
    pub unsafe fn decref(self, roc_host: &RocHost) {
        let value = self;
        unsafe { value.address.decref(roc_host); }
        unsafe { decref_erased_callable(value.on_connected, roc_host); }
        unsafe { decref_erased_callable(value.on_disconnected, roc_host); }
    }

    /// Increment Roc-owned fields.
    ///
    /// # Safety
    /// `self` must point at live Roc allocations. The retained references must
    /// be balanced by later decrefs.
    pub unsafe fn incref(self, amount: isize) {
        let value = self;
        unsafe { value.address.incref(amount); }
        unsafe { incref_erased_callable(value.on_connected, amount); }
        unsafe { incref_erased_callable(value.on_disconnected, amount); }
    }
}

impl TryType56 {
    /// Recursively decrement Roc-owned payloads.
    ///
    /// # Safety
    /// `self` must own one live Roc reference for each refcounted payload.
    pub unsafe fn decref(self, roc_host: &RocHost) {
        let value = self;
        let _ = roc_host;
        match value.tag {
            TryType56Tag::Err => {},
            TryType56Tag::Ok => {
                let payload = value.payload_ok();
                unsafe { decref_erased_callable(payload, roc_host); }
            },
        }
    }

    /// Increment Roc-owned payloads.
    ///
    /// # Safety
    /// `self` must point at live Roc allocations. The retained references must
    /// be balanced by later decrefs.
    pub unsafe fn incref(self, amount: isize) {
        let value = self;
        let _ = amount;
        match value.tag {
            TryType56Tag::Err => {},
            TryType56Tag::Ok => {
                let payload = value.payload_ok();
                unsafe { incref_erased_callable(payload, amount); }
            },
        }
    }
}

impl TerminalSettings {
    /// Recursively decrement Roc-owned fields.
    ///
    /// # Safety
    /// `self` must own one live Roc reference for each refcounted field.
    pub unsafe fn decref(self, roc_host: &RocHost) {
        let value = self;
        let _ = value;
        let _ = roc_host;
    }

    /// Increment Roc-owned fields.
    ///
    /// # Safety
    /// `self` must point at live Roc allocations. The retained references must
    /// be balanced by later decrefs.
    pub unsafe fn incref(self, amount: isize) {
        let value = self;
        let _ = value;
        let _ = amount;
    }
}

impl ViewForHostResult {
    /// Recursively decrement Roc-owned payloads.
    ///
    /// # Safety
    /// `self` must own one live Roc reference for each refcounted payload.
    pub unsafe fn decref(self, roc_host: &RocHost) {
        let value = self;
        let _ = roc_host;
        match value.tag {
            ViewForHostResultTag::Err => {},
            ViewForHostResultTag::Ok => {
                let payload = value.payload_ok();
                {
                    let list = payload;
                    if list.has_one_ref() {
                        for item_ref in list.allocation_items() {
                            let item = *item_ref;
                                unsafe { item.decref(roc_host); }
                        }
                    }
                    unsafe { list.decref(roc_host); }
                }
            },
        }
    }

    /// Increment Roc-owned payloads.
    ///
    /// # Safety
    /// `self` must point at live Roc allocations. The retained references must
    /// be balanced by later decrefs.
    pub unsafe fn incref(self, amount: isize) {
        let value = self;
        let _ = amount;
        match value.tag {
            ViewForHostResultTag::Err => {},
            ViewForHostResultTag::Ok => {
                let payload = value.payload_ok();
                unsafe { payload.incref(amount); }
            },
        }
    }
}


// Runtime Symbols
//
// The host defines these linker symbols. Compiled Roc code calls them directly.

#[allow(improper_ctypes)]
unsafe extern "C" {
    pub fn roc_alloc(length: usize, alignment: usize) -> *mut c_void;
    pub fn roc_dealloc(ptr: *mut c_void, alignment: usize);
    pub fn roc_realloc(ptr: *mut c_void, new_length: usize, alignment: usize) -> *mut c_void;
    pub fn roc_dbg(bytes: *const u8, len: usize);
    pub fn roc_expect_failed(bytes: *const u8, len: usize);
    pub fn roc_crashed(bytes: *const u8, len: usize);
}


/// Default memory management functions for Roc platform helpers.
///
/// Memory layout: each allocation prepends size metadata so that dealloc/realloc
/// can recover the original allocation size because `roc_dealloc` receives no length.
#[cfg(not(no_roc_std_helpers))]
pub struct DefaultAllocators;

#[cfg(not(no_roc_std_helpers))]
impl DefaultAllocators {
    /// Allocate memory using the Rust global allocator.
    pub extern "C" fn roc_alloc(_roc_host: *mut RocHost, length: usize, alignment: usize) -> *mut c_void {
        unsafe {
            let min_alignment = alignment.max(core::mem::align_of::<usize>());
            let size_storage_bytes = min_alignment;
            let total_size = checked_add_usize(length, size_storage_bytes, "roc_alloc allocation size overflow");

            debug_assert!(min_alignment.is_power_of_two(), "alignment must be a power of two");
            let layout = Layout::from_size_align_unchecked(total_size, min_alignment);
            let base_ptr = std::alloc::alloc(layout);
            if base_ptr.is_null() {
                eprintln!("roc_alloc: out of memory");
                std::process::exit(1);
            }

            let size_ptr = base_ptr.add(size_storage_bytes).sub(core::mem::size_of::<usize>()) as *mut usize;
            *size_ptr = total_size;

            base_ptr.add(size_storage_bytes) as *mut c_void
        }
    }

    /// Free memory previously allocated by `roc_alloc`.
    pub extern "C" fn roc_dealloc(_roc_host: *mut RocHost, ptr: *mut c_void, alignment: usize) {
        unsafe {
            let min_alignment = alignment.max(core::mem::align_of::<usize>());
            let size_storage_bytes = min_alignment;

            let size_ptr = (ptr as *const u8).sub(core::mem::size_of::<usize>()) as *const usize;
            let total_size = *size_ptr;

            let base_ptr = (ptr as *mut u8).sub(size_storage_bytes);
            debug_assert!(min_alignment.is_power_of_two(), "alignment must be a power of two");
            let layout = Layout::from_size_align_unchecked(total_size, min_alignment);
            std::alloc::dealloc(base_ptr, layout);
        }
    }

    /// Reallocate memory, preserving existing user data.
    pub extern "C" fn roc_realloc(_roc_host: *mut RocHost, ptr: *mut c_void, new_length: usize, alignment: usize) -> *mut c_void {
        unsafe {
            let min_alignment = alignment.max(core::mem::align_of::<usize>());
            let size_storage_bytes = min_alignment;

            let old_size_ptr = (ptr as *const u8).sub(core::mem::size_of::<usize>()) as *const usize;
            let old_total_size = *old_size_ptr;
            let old_base_ptr = (ptr as *mut u8).sub(size_storage_bytes);

            let new_total_size = checked_add_usize(new_length, size_storage_bytes, "roc_realloc allocation size overflow");
            debug_assert!(min_alignment.is_power_of_two(), "alignment must be a power of two");
            let old_layout = Layout::from_size_align_unchecked(old_total_size, min_alignment);
            let new_base_ptr = std::alloc::realloc(old_base_ptr, old_layout, new_total_size);
            if new_base_ptr.is_null() {
                eprintln!("roc_realloc: out of memory");
                std::process::exit(1);
            }

            let new_user_ptr = new_base_ptr.add(size_storage_bytes);
            let new_size_ptr = new_user_ptr.sub(core::mem::size_of::<usize>()) as *mut usize;
            *new_size_ptr = new_total_size;
            new_user_ptr as *mut c_void
        }
    }
}

/// Default handlers for dbg, expect-failed, and crash.
#[cfg(not(no_roc_std_helpers))]
pub struct DefaultHandlers;

#[cfg(not(no_roc_std_helpers))]
impl DefaultHandlers {
    /// Print a `dbg` expression to stderr.
    pub extern "C" fn roc_dbg(_roc_host: *mut RocHost, bytes: *const u8, len: usize) {
        unsafe {
            let msg = core::slice::from_raw_parts(bytes, len);
            let msg = core::str::from_utf8_unchecked(msg);
            eprintln!("[ROC DBG] {}", msg);
        }
    }

    /// Print a failed `expect` to stderr.
    pub extern "C" fn roc_expect_failed(_roc_host: *mut RocHost, bytes: *const u8, len: usize) {
        unsafe {
            let msg = core::slice::from_raw_parts(bytes, len);
            let msg = core::str::from_utf8_unchecked(msg);
            eprintln!("[ROC EXPECT] {}", msg);
        }
    }

    /// Print a `crash` message to stderr and exit.
    pub extern "C" fn roc_crashed(_roc_host: *mut RocHost, bytes: *const u8, len: usize) {
        unsafe {
            let msg = core::slice::from_raw_parts(bytes, len);
            let msg = core::str::from_utf8_unchecked(msg);
            eprintln!("[ROC CRASHED] {}", msg);
            std::process::exit(1);
        }
    }
}

/// Create a host-internal helper context with default memory management and handlers.
///
/// This is only for helper functions in this generated file. It is not passed to
/// compiled Roc code, which uses the direct symbol ABI declared above.
#[cfg(not(no_roc_std_helpers))]
pub fn make_roc_host(env: *mut c_void) -> RocHost {
    RocHost {
        env,
        roc_alloc: DefaultAllocators::roc_alloc,
        roc_dealloc: DefaultAllocators::roc_dealloc,
        roc_realloc: DefaultAllocators::roc_realloc,
        roc_dbg: DefaultHandlers::roc_dbg,
        roc_expect_failed: DefaultHandlers::roc_expect_failed,
        roc_crashed: DefaultHandlers::roc_crashed,
    }
}

// Provided Symbols
//
// Roc exports these symbols from the app with their natural C ABI signatures.

#[allow(improper_ctypes)]
unsafe extern "C" {
    /// Entrypoint: init_for_host
    pub fn roc_init(arg0: RocList<RocStr>) -> AnonStruct3a8854a0aa6a1ebb;

    /// Entrypoint: update_for_host
    pub fn roc_update(arg0: RocBox, arg1: RocBox) -> AnonStruct3a8854a0aa6a1ebb;

    /// Entrypoint: view_for_host
    pub fn roc_view(arg0: TerminalSettings, arg1: RocBox) -> ViewForHostResult;

    /// Entrypoint: make_event_from_str
    pub fn make_event_from_str(arg0: RocErasedCallable, arg1: RocStr) -> RocBox;

    /// Entrypoint: make_event_from_list_u8
    pub fn make_event_from_list_u8(arg0: RocErasedCallable, arg1: RocListWith<u8, false>) -> RocBox;

    /// Entrypoint: make_event_from_tcp_connected
    pub fn make_event_from_tcp_connected(arg0: RocErasedCallable, arg1: u64) -> RocBox;

    /// Entrypoint: make_event_from_tcp_disconnected
    pub fn make_event_from_tcp_disconnected(arg0: RocErasedCallable, arg1: u64) -> RocBox;

    /// Entrypoint: make_event_from_tcp_receive
    pub fn make_event_from_tcp_receive(arg0: RocErasedCallable, arg1: u64, arg2: RocListWith<u8, false>) -> RocBox;

}
